/**
 * agentBrief.ts — B57s1 (2026-07-17): the self-describing mod folder.
 *
 * Pure builders for AGENTS.md (instructions any IDE-resident coding agent reads) and
 * X4_NOTES.md (a grounding cheat-sheet distilled from EXISTING truth: census curation,
 * curated semantics, the mod's own cue index). Deterministic — no timestamps, no
 * randomness — so regeneration is idempotent and diffs only when the mod's truth changes.
 * The server endpoint assembles the input from live state; the extension writes the files.
 */

import { CENSUS_TOP_52_TAGS } from './nodeToolbox';
import { getElementSemantics } from './mdSemantics';

export interface AgentBriefInput {
  modId: string;
  /** loaded project files (relative, forward slashes) */
  files: string[];
  /** files owned by the canvas compiler — hand edits get overwritten on recompile */
  generatedFiles: string[];
  /** routed schema domains present in this mod (factions, gamestarts, addon, diff, t, …) */
  domainsPresent: string[];
  /** the mod's own cue names (from the cue index) */
  cueNames: string[];
  /** MCP tool names exposed by the x4forge shim */
  mcpTools: string[];
}

const GENERATED_HEADER = (name: string) =>
  `<!-- GENERATED by X4 Forge (${name}) — regenerated on demand; hand edits will be lost. -->`;

export function buildAgentsMd(input: AgentBriefInput): string {
  const generated = input.generatedFiles.length
    ? input.generatedFiles.map(f => `- \`${f}\``).join('\n')
    : '- (none detected)';
  const editable = input.files.filter(f => !input.generatedFiles.includes(f));
  return `${GENERATED_HEADER('AGENTS.md')}
# Agent instructions — X4 mod \`${input.modId}\`

This folder is an X4: Foundations mod managed by **X4 Forge**. The Forge's validator is the
single referee for correctness in this folder. Follow THE RULE below for every change.

## THE RULE (non-negotiable loop)
1. Propose a change (draft it — use \`author_check\` to validate a draft BEFORE writing).
2. Validate: call the \`validate_mod\` / \`stage_and_validate\` MCP tool (server \`x4forge\`).
3. Fix every finding the validator returns (findings carry file/line/code and, where known,
   deterministic remediation hints).
4. Re-validate until findings are clear.
5. **Done is defined by the \`readiness\` tool, not by your judgment** — a change is complete
   only when the readiness ladder's machine stages pass. Never claim success with open
   findings or a failing readiness stage.

## File ownership — DO NOT hand-edit generated files
These files are compiled from the Forge's visual canvas; hand edits are overwritten:
${generated}

Hand-editable files (still validate after every edit):
${editable.slice(0, 40).map(f => `- \`${f}\``).join('\n') || '- (none)'}

## Facts about this mod
- Schema domains present: ${input.domainsPresent.length ? input.domainsPresent.join(', ') : '(none routed)'}
- Cues defined here: ${input.cueNames.length ? input.cueNames.slice(0, 30).map(c => `\`${c}\``).join(', ') : '(none)'}
- Grounding notes: see \`X4_NOTES.md\` (same folder) before authoring MD.

## Available x4forge MCP tools
${input.mcpTools.map(t => `- \`${t}\``).join('\n')}

## Hard boundaries
- Never rename released cues or scripts (breaks players' saved games).
- Never invent element or attribute names — if the validator or \`explain_element\` doesn't
  know it, it does not exist.
- Deploys and spending are user-gated; your job ends at validated, readiness-green files.
`;
}

export function buildNotesMd(input: AgentBriefInput): string {
  const rows: string[] = [];
  for (const tag of CENSUS_TOP_52_TAGS.slice(0, 20)) {
    const sem = getElementSemantics(tag);
    if (!sem) continue;
    let desc = '';
    try { desc = sem.describe({}); } catch { /* deterministic describe must not throw */ }
    rows.push(`| \`${tag}\` | ${sem.title} | ${desc.replace(/\|/g, '\\|')} |`);
  }
  return `${GENERATED_HEADER('X4_NOTES.md')}
# X4 modding grounding notes — for coding agents

Distilled from the game's own schema, the Forge's vanilla-usage census (which actions real
Egosoft content actually uses), and the Forge's curated deterministic semantics. Prefer these
elements — they are the proven 90% of real MD usage.

## Structure every MD file follows
\`\`\`xml
<mdscript name="ScriptName">
  <cues>
    <cue name="Cue_Name" instantiate="true">
      <conditions><event_cue_signalled cue="md.Other.Cue"/></conditions>
      <actions><!-- actions here --></actions>
    </cue>
  </cues>
</mdscript>
\`\`\`
- Events/conditions live under \`<conditions>\`; actions under \`<actions>\`.
- Cue names are permanent once released (saved-game contract).
- Use \`explain_element\` (MCP) or hover (IDE) for any element's attributes and semantics.

## Census-proven elements (top of real vanilla usage)
| element | what it is | deterministic description |
|---|---|---|
${rows.join('\n')}

## This mod
- Domains: ${input.domainsPresent.join(', ') || '(md only)'}
- Own cues (reference targets for \`event_cue_signalled\`): ${input.cueNames.slice(0, 30).map(c => `\`${c}\``).join(', ') || '(none yet)'}
`;
}

/* ------------------------------------------------------------------ *
 * Oracle — fixture input; asserts the load-bearing content, not prose.
 * ------------------------------------------------------------------ */

export function runAgentBriefSelftest() {
  const checks: { name: string; pass: boolean; detail?: string }[] = [];
  const ok = (name: string, pass: boolean, detail?: string) => checks.push({ name, pass, ...(detail ? { detail } : {}) });

  const input: AgentBriefInput = {
    modId: 'test_mod',
    files: ['content.xml', 'md/test_mod.xml', 'md/handmade.xml', 'libraries/factions.xml'],
    generatedFiles: ['md/test_mod.xml', 'content.xml'],
    domainsPresent: ['factions'],
    cueNames: ['Boot_Cue', 'Reward_Cue'],
    mcpTools: ['validate_mod', 'readiness', 'explain_element'],
  };
  const agents = buildAgentsMd(input);
  ok('agents_generated_header', agents.startsWith('<!-- GENERATED'));
  ok('agents_names_the_rule_tools', agents.includes('`validate_mod`') && agents.includes('`readiness`'));
  ok('agents_marks_generated_files', agents.includes('`md/test_mod.xml`'));
  ok('agents_editable_excludes_generated', /Hand-editable[\s\S]*`md\/handmade\.xml`/.test(agents) && !/Hand-editable[\s\S]*`md\/test_mod\.xml`/.test(agents));
  ok('agents_lists_cues', agents.includes('`Boot_Cue`'));
  ok('agents_rename_boundary', /Never rename released cues/.test(agents));
  ok('agents_done_is_readiness', /Done is defined by the `readiness` tool/.test(agents));

  const notes = buildNotesMd(input);
  ok('notes_generated_header', notes.startsWith('<!-- GENERATED'));
  ok('notes_has_census_rows', (notes.match(/^\| `/gm) || []).length >= 10, `rows=${(notes.match(/^\| `/gm) || []).length}`);
  ok('notes_curated_semantics_present', /Set Variable|Debug Text/.test(notes));
  ok('notes_mod_cues_listed', notes.includes('`Reward_Cue`'));
  ok('deterministic_idempotent', buildAgentsMd(input) === agents && buildNotesMd(input) === notes);

  const passed = checks.filter(c => c.pass).length;
  return { allPassed: passed === checks.length, passed, total: checks.length, checks };
}
