/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * B24 slice 2 (ADR-F3) — the FORGE-STATE probe-extension GENERATOR.
 *
 * The Forge builds a tiny, OPTIONAL, READ-ONLY extension (`x4_forge_probe`) whose only
 * job is to emit `FORGE-STATE <topic> {json}` lines to the debug log, which the B24s1
 * Inspector then renders. Binding ADR-F3 constraints, enforced by the oracle:
 *   - READ-ONLY: the generated MD contains ONLY debug_text actions — no game-state
 *     mutation (no create_*, set_value, reward_*, …). Verified structurally.
 *   - OPTIONAL / ZERO-IMPACT-ABSENT: it's a standalone extension; nothing in the Forge
 *     or the mod under construction depends on it.
 *   - SAVE-REMOVABLE: debug_text writes nothing persistent to the save.
 *
 * This module only GENERATES + validates the probe (reaches ◐: oracle-green, compiles
 * clean, round-trips through the parser). Actually DEPLOYING it into the game dirs and
 * confirming FORGE-STATE in-game is the write-gated / in-game half (Ken).
 *
 * The probe is EVENT-BASED (emits on game start and on every /refreshmd). A periodic
 * timer heartbeat needs a `checkinterval` cue-attribute the MD emitter does not yet
 * write — that's a documented follow-up, not this slice.
 */

import type { MDNode, MDLink, ModWorkspace } from '../types';
import { sanitizeWorkspace, generateMDXML, validateModWorkspace } from '../types';
import { buildStateTextExpression, parseForgeState } from './forgeState';

export interface ProbeTopic {
  topic: string;
  fields: Array<{ key: string; expression: string }>;
}

/**
 * Default read-only snapshot topics. The MD EXPRESSIONS here are plausible but their
 * in-game resolution is exactly what Ken verifies on deploy (a wrong property logs an
 * error, not a crash — the probe is read-only). The GENERATOR mechanism is what this
 * slice proves.
 */
export const DEFAULT_PROBE_TOPICS: ProbeTopic[] = [
  { topic: 'player', fields: [
    { key: 'name', expression: 'player.name' },
    { key: 'credits', expression: 'player.money' },
    { key: 'sector', expression: 'player.sector.name' },
  ] },
  { topic: 'assets', fields: [
    { key: 'ships', expression: 'player.numships' },
    { key: 'stations', expression: 'player.numstations' },
  ] },
];

const N = (id: string, type: MDNode['type'], xmlTag: string, x: number, y: number, properties: Record<string, unknown> = {}): Partial<MDNode> =>
  ({ id, type, xmlTag, x, y, properties, label: xmlTag });
const L = (id: string, s: string, sp: string, t: string, tp: string): MDLink =>
  ({ id, sourceNodeId: s, sourcePortId: sp, targetNodeId: t, targetPortId: tp });

/**
 * Generate the `x4_forge_probe` workspace: one event_game_started cue whose actions are
 * a chain of debug_text emits, one per topic. Deterministic (no wall-clock / randomness).
 */
export function buildProbeWorkspace(topics: ProbeTopic[] = DEFAULT_PROBE_TOPICS): ModWorkspace {
  const nodes: Partial<MDNode>[] = [
    N('probe_cue', 'cue', 'cue', 80, 80, { name: 'Forge_Probe_Snapshot', namespace: 'this' }),
    N('probe_evt', 'event', 'event_game_started', 80, 300, {}),
  ];
  const links: MDLink[] = [L('l_cond', 'probe_cue', 'out_cond', 'probe_evt', 'in_cond')];

  let prevActionId: string | null = null;
  (topics.length ? topics : DEFAULT_PROBE_TOPICS).forEach((t, i) => {
    const id = `emit_${i}`;
    nodes.push(N(id, 'action', 'debug_text', 460, 60 + i * 130, { text: buildStateTextExpression(t.topic, t.fields) }));
    if (prevActionId === null) links.push(L('l_act', 'probe_cue', 'out_act', id, 'in_act'));
    else links.push(L(`l_next_${i}`, prevActionId, 'out_next', id, 'in_act'));
    prevActionId = id;
  });

  return sanitizeWorkspace({
    name: 'x4_forge_probe',
    description: 'Optional read-only FORGE-STATE probe generated by X4 Forge (ADR-F3). Emits game-state snapshots to the debug log on game start / refreshmd. Remove it any time; it writes nothing to your save.',
    nodes,
    links,
    uiWidgets: [],
  } as Partial<ModWorkspace>);
}

/* ------------------------------------------------------------------ *
 * Oracle — house contract.
 * ------------------------------------------------------------------ */

export function runForgeProbeSelftest(): {
  allPassed: boolean; pass: boolean; passed: number; total: number;
  checks: { name: string; pass: boolean; detail?: string }[];
} {
  const checks: { name: string; pass: boolean; detail?: string }[] = [];
  const ok = (name: string, cond: boolean, detail?: unknown) =>
    checks.push({ name, pass: !!cond, detail: detail === undefined ? undefined : (typeof detail === 'string' ? detail : JSON.stringify(detail)) });

  const ws = buildProbeWorkspace();
  const md = generateMDXML(ws);

  // 1. compiles clean — same authoritative bar as templates/patterns.
  const diags = validateModWorkspace(ws, md);
  const errors = diags.filter(d => d.severity === 'error');
  ok('probe compiles to zero validation errors', errors.length === 0, errors.map(e => e.message));

  // 2. READ-ONLY invariant (ADR-F3): every action node is debug_text, nothing that mutates.
  const actions = ws.nodes.filter(n => n.type === 'action');
  ok('every action is debug_text (read-only)', actions.length > 0 && actions.every(a => a.xmlTag === 'debug_text'),
    actions.map(a => a.xmlTag).join(','));

  // 3. one emit per topic, in a cue triggered by event_game_started.
  ok('event-based (event_game_started trigger)', ws.nodes.some(n => n.xmlTag === 'event_game_started'));
  ok('one emit action per topic', actions.length === DEFAULT_PROBE_TOPICS.length, `${actions.length} vs ${DEFAULT_PROBE_TOPICS.length}`);

  // 4. the emitted XML carries a FORGE-STATE marker per topic, XML-escaped (&quot;, no raw ").
  const markersPresent = DEFAULT_PROBE_TOPICS.every(t => md.includes(`FORGE-STATE ${t.topic} {`));
  ok('MD carries a FORGE-STATE marker per topic', markersPresent);
  ok('emitted MD escapes JSON quotes (&quot;, no raw quote in the JSON)', md.includes('&quot;') && !md.includes('{"'),
    md.includes('{"') ? 'found raw {" in emitted MD' : 'ok');

  // 5. parser-compatibility: a rendered snapshot (what X4 would log) round-trips through
  //    parseForgeState with the exact key set the probe emits.
  const playerTopic = DEFAULT_PROBE_TOPICS[0];
  const renderedLine = `[=ERROR=] 10.0 Error ... FORGE-STATE ${playerTopic.topic} {` +
    playerTopic.fields.map(f => `"${f.key}": "sample"`).join(', ') + '}';
  const parsed = parseForgeState(renderedLine);
  const t0 = parsed.topics.find(x => x.topic === playerTopic.topic);
  ok('rendered snapshot round-trips with the probe key set',
    !!t0 && playerTopic.fields.every(f => Object.prototype.hasOwnProperty.call(t0.data as object, f.key)),
    t0 ? JSON.stringify(t0.data) : 'no topic');

  // 6. deterministic — identical output on re-generation (no wall-clock/randomness).
  ok('deterministic re-generation', generateMDXML(buildProbeWorkspace()) === md);

  // 7. custom topics parameterize.
  const custom = buildProbeWorkspace([{ topic: 'factions', fields: [{ key: 'argon', expression: 'faction.argon.relation' }] }]);
  const customMd = generateMDXML(custom);
  ok('custom topics parameterize', customMd.includes('FORGE-STATE factions {')
    && validateModWorkspace(custom, customMd).filter(d => d.severity === 'error').length === 0);

  const passed = checks.filter(c => c.pass).length;
  const allPassed = passed === checks.length;
  return { allPassed, pass: allPassed, passed, total: checks.length, checks };
}
