/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ModWorkspace, generateMDXML, generateUIXML, generateUIIndexXML, generateUILuaScript, XMLDiagnostic } from '../types';
import { generateHttpGlueLua, generateContractMdScript, validateContract } from './contractGlue';

export const toSafeModId = (name: string): string => {
  const safe = name
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_+|_+$/g, '');
  return safe || 'x4_md_studio_mod';
};

export const toContentVersion = (value: string): string => {
  const normalized = String(value || '').trim().match(/^\d+(?:\.\d+)?/)?.[0];
  const numericVersion = normalized ? Number.parseFloat(normalized) : 1;
  const contentVersion = Number.isFinite(numericVersion)
    ? Math.round(numericVersion * 100)
    : 100;

  return String(Math.max(1, contentVersion));
};

export const escapeXmlAttr = (str: string): string => {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
};

export const escapeXmlText = (str: string): string => {
  return (str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
};

export const toTFileName = (file: any): string => {
  const explicitName = String(file?.fileName || '').trim();
  if (explicitName) {
    const match = explicitName.match(/^(.+?)-[lL](\d+)\.xml$/);
    if (match) {
      return `${match[1]}-l${match[2].padStart(3, '0')}.xml`;
    }
    return explicitName;
  }

  const languageId = String(file?.languageId || '44').replace(/\D/g, '') || '44';
  return `0001-l${languageId.padStart(3, '0')}.xml`;
};

export const generateContentXML = (modId: string, workspace: ModWorkspace): string => {
  const today = new Date().toISOString().slice(0, 10);
  const displayName = workspace.name || modId;
  const description = workspace.description || 'Generated by X4:MD Studio';
  const author = workspace.author || 'X4:MD Studio';
  return `<?xml version="1.0" encoding="utf-8"?>\n<content id="${escapeXmlAttr(modId)}" name="${escapeXmlAttr(displayName)}" description="${escapeXmlAttr(description)}" author="${escapeXmlAttr(author)}" version="${toContentVersion(workspace.version)}" date="${today}" save="0" enabled="1">\n  <text language="44" name="${escapeXmlAttr(displayName)}" description="${escapeXmlAttr(description)}" author="${escapeXmlAttr(author)}" />\n</content>\n`;
};

export const compileScriptToXML = (script: any): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<aiscript name="${escapeXmlAttr(script.name)}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="aiscripts.xsd">\n`;
  xml += `  <!-- X4 Foundations Autopilot & Task Script Behavior -->\n`;
  xml += `  <!-- Generated visually using X4 Mod Studio Behaviors Suite -->\n`;
  xml += `  <params>\n`;
  (script.params || []).forEach((p: any) => {
    xml += `    <param name="${escapeXmlAttr(p.name)}" type="${escapeXmlAttr(p.type)}" default="${escapeXmlAttr(p.defaultValue)}" comment="${escapeXmlAttr(p.comment)}" />\n`;
  });
  xml += `  </params>\n`;

  if (script.interrupts && script.interrupts.length > 0) {
    xml += `  <interrupts>\n`;
    script.interrupts.forEach((int: any) => {
      xml += `    <handler event="${escapeXmlAttr(int.event)}">\n`;
      xml += `      <actions>\n`;
      if (int.action === 'flee') {
        xml += `        <run_script name="'move.flee'" />\n`;
      } else if (int.action === 'dock_at_safety') {
        xml += `        <run_script name="'move.dockat'" />\n`;
      } else {
        xml += `        <write_to_logbook text="'Interrupt event fired: ${escapeXmlAttr(int.event)}'" />\n`;
      }
      xml += `      </actions>\n`;
      xml += `    </handler>\n`;
    });
    xml += `  </interrupts>\n`;
  }

  xml += `  <attention min="${escapeXmlAttr(script.attentionLevel || 'low')}">\n`;
  xml += `    <actions>\n`;
  xml += `      <label name="start" />\n`;

  (script.actions || []).forEach((act: any) => {
    xml += `      <!-- Action: ${escapeXmlText(act.label)} -->\n`;
    switch (act.command) {
      case 'move_to':
        xml += `      <move_to object="this.ship" destination="${escapeXmlAttr(act.properties.destination || '$target')}" forceposition="false" finishonfound="true">\n`;
        xml += `        <interrupt_after_time time="10s" />\n`;
        xml += `      </move_to>\n`;
        break;
      case 'flee':
        xml += `      <run_script name="'move.flee'" />\n`;
        break;
      case 'shoot':
        xml += `      <shoot_at object="this.ship" target="${escapeXmlAttr(act.properties.target || '$enemy')}" turretmode="attackhostile" />\n`;
        break;
      case 'dock_at':
        xml += `      <dock_at object="this.ship" station="${escapeXmlAttr(act.properties.station || '$station')}" />\n`;
        break;
      case 'wait':
        if (act.properties.exact) {
          xml += `      <wait exact="${escapeXmlAttr(act.properties.exact)}" />\n`;
        } else {
          xml += `      <wait min="${escapeXmlAttr(act.properties.min || '2s')}" max="${escapeXmlAttr(act.properties.max || '10s')}" />\n`;
        }
        break;
      case 'find_objects':
        xml += `      <find_object name="$targets" class="class.${escapeXmlAttr(act.properties.class || 'ship')}" space="player.sector" multiple="true" />\n`;
        break;
      case 'custom_xml':
        xml += `      ${act.properties.rawXml || '<!-- custom nodes -->'}\n`;
        break;
    }
  });

  xml += `    </actions>\n`;
  xml += `  </attention>\n`;
  xml += `</aiscript>`;
  return xml;
};

export const compileWaresXML = (wares: any[]): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<diff>\n`;
  xml += `  <!-- XML Diff Patch adding to core wares database file: libraries/wares.xml -->\n`;
  xml += `  <add sel="/wares">\n`;
  wares.forEach((item: any) => {
    const tagsAttr = item.tags ? ` tags="${escapeXmlAttr(item.tags)}"` : '';
    const productionMethod = item.productionMethod || 'default';
    const productionNameAttr = item.productionName ? ` name="${escapeXmlAttr(item.productionName)}"` : '';
    const primaryWares = Array.isArray(item.primaryWares)
      ? item.primaryWares.filter((ware: any) => String(ware?.ware || '').trim() && Number(ware?.amount) > 0)
      : [];

    xml += `    <ware id="${escapeXmlAttr(item.id)}" name="${escapeXmlAttr(item.name)}" description="${escapeXmlAttr(item.description)}" transport="${escapeXmlAttr(item.transport)}" volume="${item.volume}"${tagsAttr}>\n`;
    xml += `      <price min="${item.minPrice}" average="${item.avgPrice}" max="${item.maxPrice}" />\n`;
    xml += `      <production time="${item.prodTime}" amount="${item.prodAmount}" method="${escapeXmlAttr(productionMethod)}"${productionNameAttr}`;
    if (primaryWares.length === 0) {
      xml += ` />\n`;
    } else {
      xml += `>\n`;
      xml += `        <primary>\n`;
      primaryWares.forEach((ware: any) => {
        xml += `          <ware ware="${escapeXmlAttr(ware.ware)}" amount="${escapeXmlAttr(String(ware.amount))}" />\n`;
      });
      xml += `        </primary>\n`;
      xml += `      </production>\n`;
    }
    xml += `    </ware>\n`;
  });
  xml += `  </add>\n`;
  xml += `</diff>`;
  return xml;
};

export const compileJobsXML = (jobs: any[]): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<diff>\n`;
  xml += `  <!-- XML Diff Patch adding new AI pilot squad to core jobs database: libraries/jobs.xml -->\n`;
  xml += `  <add sel="/jobs">\n`;
  jobs.forEach((item: any) => {
    xml += `    <job id="${escapeXmlAttr(item.id)}" name="${escapeXmlAttr(item.name)}" active="true">\n`;
    xml += `      <expiration min="7200" max="14400" />\n`;
    xml += `      <modifiers rebuild="${item.rebuildOnDestroy ? 'true' : 'false'}" />\n`;
    xml += `      <ship>\n`;
    xml += `        <select faction="${escapeXmlAttr(item.faction)}" tags="military ${escapeXmlAttr(item.shipClass)}" />\n`;
    xml += `        <loadout>\n`;
    xml += `          <level min="0.8" max="1.0" />\n`;
    xml += `        </loadout>\n`;
    xml += `      </ship>\n`;
    xml += `      <quota galaxy="${item.galaxyQuota}" sector="${item.sectorQuota}" />\n`;
    xml += `      <task script="${escapeXmlAttr(item.taskScript)}" />\n`;
    xml += `    </job>\n`;
  });
  xml += `  </add>\n`;
  xml += `</diff>`;
  return xml;
};

export const compileTFileXML = (file: any): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<language id="${escapeXmlAttr(file.languageId)}">\n`;
  (file.pages || []).forEach((page: any) => {
    const title = page.title ? ` title="${escapeXmlAttr(page.title)}"` : '';
    xml += `  <page id="${escapeXmlAttr(page.id)}"${title}>\n`;
    (page.items || []).forEach((item: any) => {
      const comment = item.description ? ` <!-- ${escapeXmlText(item.description)} -->` : '';
      xml += `    <t id="${escapeXmlAttr(item.id)}">${escapeXmlText(item.value)}</t>${comment}\n`;
    });
    xml += `  </page>\n`;
  });
  xml += `</language>`;
  return xml;
};

export const compileDiffDocument = (patches: any[], targetFile: string): string => {
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- XML Diff patch targeting file: "${escapeXmlAttr(targetFile)}" -->\n`;
  xml += `<diff>\n\n`;
  patches.forEach((b: any) => {
    if (b.note) {
      xml += `  <!-- Patch Note: ${escapeXmlText(b.note)} -->\n`;
    }
    if (b.action === 'remove') {
      xml += `  <remove sel="${escapeXmlAttr(b.sel)}" />\n\n`;
    } else {
      const posAttr = (b.action === 'add' && b.pos) ? ` pos="${escapeXmlAttr(b.pos)}"` : '';
      xml += `  <${b.action} sel="${escapeXmlAttr(b.sel)}"${posAttr}>\n`;
      const lines = (b.content || '').split('\n').filter((l: string) => l.trim().length > 0);
      lines.forEach((l: string) => {
        xml += `    ${l}\n`;
      });
      xml += `  </${b.action}>\n\n`;
    }
  });
  xml += `</diff>`;
  return xml;
};

export const writeTextFile = async (directoryHandle: any, filename: string, content: string) => {
  const fileHandle = await directoryHandle.getFileHandle(filename, { create: true });
  const writable = await fileHandle.createWritable();
  await writable.write(content);
  await writable.close();
};

export const writeTextFileAtPath = async (baseHandle: any, filePath: string, content: string) => {
  const parts = filePath.split('/');
  let currentDir = baseHandle;
  for (let i = 0; i < parts.length - 1; i++) {
    currentDir = await currentDir.getDirectoryHandle(parts[i], { create: true });
  }
  const filename = parts[parts.length - 1];
  const fileHandle = await currentDir.getFileHandle(filename, { create: true });
  const writable = await fileHandle.createWritable();
  await writable.write(content);
  await writable.close();
};

export const validatePackageReadiness = (workspace: ModWorkspace): XMLDiagnostic[] => {
  const reports: XMLDiagnostic[] = [];
  const modId = toSafeModId(workspace.name);

  if (!workspace.name?.trim()) {
    reports.push({
      severity: 'error',
      message: 'Compiled extension needs a mod name. This becomes the content.xml name and package folder.',
      category: 'egosoft'
    });
  }

  if (!/^[a-z0-9_]+$/.test(modId)) {
    reports.push({
      severity: 'error',
      message: `Compiled extension id "${modId}" must use lowercase letters, numbers, and underscores only.`,
      category: 'egosoft'
    });
  }

  if (!workspace.author?.trim()) {
    reports.push({
      severity: 'warning',
      message: 'Compiled content.xml has no explicit author. Set Mod Meta author before shipping.',
      category: 'egosoft'
    });
  }

  if (!workspace.description?.trim()) {
    reports.push({
      severity: 'warning',
      message: 'Compiled content.xml has no explicit description. Manual users need this in the Extensions menu.',
      category: 'egosoft'
    });
  }

  if (!workspace.nodes.some(node => node.type === 'cue')) {
    reports.push({
      severity: 'error',
      message: 'Compiled MD package has no cue nodes. The extension can load, but the MD script has no executable entry point.',
      category: 'egosoft'
    });
  }

  return reports;
};

const MAX_SNAPSHOTS = 30;

/**
 * Writes a timestamped JSON snapshot of the workspace into <modDir>/.snapshots/.
 * Used to build a durable, rollback-able version history alongside the mod.
 * Non-fatal: a snapshot failure never blocks a compile.
 */
export const writeSnapshot = async (targetDir: any, workspace: ModWorkspace): Promise<void> => {
  try {
    const snapDir = await targetDir.getDirectoryHandle('.snapshots', { create: true });
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    await writeTextFile(
      snapDir,
      `snapshot_${stamp}.json`,
      JSON.stringify({ savedAt: new Date().toISOString(), name: workspace.name, workspace }, null, 2)
    );
    // Prune oldest snapshots beyond the cap (names sort chronologically by ISO stamp).
    const names: string[] = [];
    for await (const [name, handle] of (snapDir as any).entries()) {
      if ((handle as any).kind === 'file' && name.startsWith('snapshot_') && name.endsWith('.json')) {
        names.push(name);
      }
    }
    names.sort();
    for (let i = 0; i < names.length - MAX_SNAPSHOTS; i++) {
      await (snapDir as any).removeEntry(names[i]);
    }
  } catch (err) {
    console.warn('Snapshot write failed (non-fatal):', err);
  }
};

/** Lists available snapshots for a mod, newest first. */
export const listSnapshots = async (dirHandle: any, modId: string): Promise<{ name: string; savedAt: string }[]> => {
  try {
    const modDir = await dirHandle.getDirectoryHandle(modId);
    const snapDir = await modDir.getDirectoryHandle('.snapshots');
    const out: { name: string; savedAt: string }[] = [];
    for await (const [name, handle] of (snapDir as any).entries()) {
      if ((handle as any).kind === 'file' && name.endsWith('.json')) {
        out.push({ name, savedAt: name.replace('snapshot_', '').replace('.json', '') });
      }
    }
    return out.sort((a, b) => b.name.localeCompare(a.name));
  } catch {
    return [];
  }
};

/** Reads a single snapshot back into a workspace object for restore. */
export const readSnapshot = async (dirHandle: any, modId: string, snapshotName: string): Promise<ModWorkspace | null> => {
  try {
    const modDir = await dirHandle.getDirectoryHandle(modId);
    const snapDir = await modDir.getDirectoryHandle('.snapshots');
    const fileHandle = await snapDir.getFileHandle(snapshotName);
    const file = await fileHandle.getFile();
    const parsed = JSON.parse(await file.text());
    return parsed.workspace || parsed;
  } catch {
    return null;
  }
};

export const compileAndSaveAll = async (
  originalWorkspace: ModWorkspace,
  dirHandle: any,
  mode: 'candy' | 'store',
  options: { snapshot?: boolean } = {}
): Promise<{ success: boolean; message: string }> => {
  if (!dirHandle) {
    throw new Error('No directory linked.');
  }

  // Filter out any items the user has excluded from the current build output
  const activeNodes = (originalWorkspace.nodes || []).filter(n => n.includeInBuild !== false);
  const activeWidgets = (originalWorkspace.uiWidgets || []).filter(w => w.includeInBuild !== false);
  const activeAiScripts = (originalWorkspace.aiScripts || []).filter(s => s.includeInBuild !== false);
  const activeWares = (originalWorkspace.wares || []).filter(w => w.includeInBuild !== false);
  const activeJobs = (originalWorkspace.jobs || []).filter(j => j.includeInBuild !== false);
  const activeTFiles = (originalWorkspace.tFiles || []).filter(f => f.includeInBuild !== false);
  const activeXmlPatches = (originalWorkspace.xmlPatches || []).filter(p => p.includeInBuild !== false);

  const workspace = {
    ...originalWorkspace,
    nodes: activeNodes,
    uiWidgets: activeWidgets,
    aiScripts: activeAiScripts,
    wares: activeWares,
    jobs: activeJobs,
    tFiles: activeTFiles,
    xmlPatches: activeXmlPatches
  };

  const errors = validatePackageReadiness(workspace).filter(r => r.severity === 'error');
  if (errors.length > 0) {
    throw new Error(errors.map(e => e.message).join(' '));
  }

  const modId = toSafeModId(workspace.name);
  
  // Decide whether the target handle is the mod root directly (candy) or if we create/use a subfolder (candy store)
  let targetDir = dirHandle;
  if (mode === 'store') {
    targetDir = await dirHandle.getDirectoryHandle(modId, { create: true });
  }

  // 1. Manifest content.xml and README.md
  await writeTextFile(targetDir, 'content.xml', generateContentXML(modId, workspace));
  await writeTextFile(targetDir, 'README.md', `# ${workspace.name || modId}\n\nGenerated by X4:MD Studio.\n\nInstall location:\n\n\`\`\`\nX4 Foundations/extensions/${modId}/\n\`\`\`\n\nRuntime reload during development: save files, then run \`refreshmd\` in X4's debug command input.\n`);

  // 2. Mission Director (md) script
  const directorDir = await targetDir.getDirectoryHandle('md', { create: true });
  await writeTextFile(directorDir, `${modId}.xml`, generateMDXML(workspace));
  // Lever 2: MD bridge cues for the HTTP integration contract (paired with ui/<modId>_http.lua).
  if (workspace.integrationContract && validateContract(workspace.integrationContract).filter(fd => fd.severity === 'error').length === 0) {
    await writeTextFile(directorDir, `${modId}_http.xml`, generateContractMdScript(workspace.integrationContract, `${modId}_http`));
  }

  // 3. UI — X4-correct: extension-root ui.xml registering Lua entries under ui/.
  //    Includes the generated HTTP-integration glue (Lever 2) when a valid contract exists.
  const contract = workspace.integrationContract;
  const contractValid = !!contract && validateContract(contract).filter(fd => fd.severity === 'error').length === 0;
  const hasWidgets = !!workspace.uiWidgets?.length;
  if (hasWidgets || contractValid) {
    const uiFiles: string[] = [];
    if (hasWidgets) uiFiles.push(`ui/${modId}.lua`);
    if (contractValid) uiFiles.push(`ui/${modId}_http.lua`);
    const uiIndex = `<?xml version="1.0" encoding="utf-8"?>\n<addon name="${modId}" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../ui/core/addon.xsd">\n  <environment type="menus">\n${uiFiles.map(p => `    <file name="${p}" />`).join("\n")}\n  </environment>\n</addon>`;
    await writeTextFile(targetDir, 'ui.xml', uiIndex);
    const uiDir = await targetDir.getDirectoryHandle('ui', { create: true });
    if (hasWidgets) await writeTextFile(uiDir, `${modId}.lua`, generateUILuaScript(workspace, modId));
    if (contractValid) await writeTextFile(uiDir, `${modId}_http.lua`, generateHttpGlueLua(contract!));
  }

  // 4. AIScripts behavior trees
  if (workspace.aiScripts?.length) {
    const aiDir = await targetDir.getDirectoryHandle('aiscripts', { create: true });
    for (const script of workspace.aiScripts) {
      const fileName = script.name.endsWith('.xml') ? script.name : `${script.name}.xml`;
      await writeTextFile(aiDir, fileName, compileScriptToXML(script));
    }
  }

  // 5. Libraries (Wares / Jobs)
  if (workspace.wares?.length || workspace.jobs?.length) {
    const libDir = await targetDir.getDirectoryHandle('libraries', { create: true });
    if (workspace.wares?.length) {
      await writeTextFile(libDir, 'wares.xml', compileWaresXML(workspace.wares));
    }
    if (workspace.jobs?.length) {
      await writeTextFile(libDir, 'jobs.xml', compileJobsXML(workspace.jobs));
    }
  }

  // 6. Translation files
  if (workspace.tFiles?.length) {
    const tDir = await targetDir.getDirectoryHandle('t', { create: true });
    for (const tFile of workspace.tFiles) {
      await writeTextFile(tDir, toTFileName(tFile), compileTFileXML(tFile));
    }
  }

  // 7. XML diff patches grouped by file
  if (workspace.xmlPatches?.length) {
    const patchesByFile: Record<string, any[]> = {};
    workspace.xmlPatches.forEach((patch: any) => {
      const file = patch.targetFile || 'libraries/wares.xml';
      if (!patchesByFile[file]) {
        patchesByFile[file] = [];
      }
      patchesByFile[file].push(patch);
    });

    for (const [filePath, filePatches] of Object.entries(patchesByFile)) {
      await writeTextFileAtPath(targetDir, filePath, compileDiffDocument(filePatches, filePath));
    }
  }

  // 8. Version snapshot (rollback history) inside the mod folder, when requested.
  if (options.snapshot && mode === 'store') {
    await writeSnapshot(targetDir, workspace);
  }

  return {
    success: true,
    message: mode === 'store' 
      ? `Successfully compiled extension inside subdirectory extensions/${modId}/`
      : `Successfully compiled extension directly into connected folder at root.`
  };
};
