/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import express from "express";
import path from "path";
import dotenv from "dotenv";
import crypto from "crypto";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import { createEmptySchemaLibrary, loadSchemaLibrary, readXsdConfig, resolveXsdConfig, writeXsdConfig } from "./src/lib/xsdParser";

// Import types & helpers from the frontend shared file
import {
  generateMDXML,
  generateUIXML,
  validateModWorkspace,
  X4_FACTIONS,
  X4_SHIP_MACROS,
  X4_STATION_MACROS,
  X4_SOUND_EFFECTS,
  NODE_TEMPLATES,
  PRESETS,
  ModWorkspace,
  sanitizeWorkspace
} from "./src/types";
import {
  toSafeModId,
  generateContentXML,
  compileScriptToXML,
  compileWaresXML,
  compileJobsXML,
  compileTFileXML,
  compileDiffDocument,
  validatePackageReadiness
} from "./src/lib/modCompiler";
import type { SchemaLibrary } from "./src/lib/schemaTypes";

dotenv.config();
// Also load .env.local (Vite convention) so values like GITHUB_CLIENT_ID and GEMINI_API_KEY
// placed there are visible to the server. .env.local takes precedence.
dotenv.config({ path: '.env.local', override: true });

const app = express();
const PORT = Number(process.env.PORT || 3000);
const TOKEN_FILE = path.join(process.cwd(), ".studio-api-token");

function loadStudioApiToken(): string {
  if (process.env.STUDIO_API_TOKEN?.trim()) {
    return process.env.STUDIO_API_TOKEN.trim();
  }
  try {
    const existing = fs.readFileSync(TOKEN_FILE, "utf8").trim();
    if (existing) {
      return existing;
    }
  } catch {
    // First run on this checkout; create a local-only token below.
  }
  const token = crypto.randomBytes(32).toString("hex");
  fs.writeFileSync(TOKEN_FILE, token, { encoding: "utf8" });
  return token;
}

const STUDIO_API_TOKEN = loadStudioApiToken();

function injectStudioToken(html: string): string {
  const tokenScript = `<script>window.__STUDIO_API_TOKEN__=${JSON.stringify(STUDIO_API_TOKEN)};</script>`;
  return html.replace("</head>", `  ${tokenScript}\n  </head>`);
}

function loadCurrentSchemaLibrary(): SchemaLibrary {
  try {
    const resolved = resolveXsdConfig();
    const library = loadSchemaLibrary(resolved.schemaDir, resolved.schemaFiles || ['md.xsd', 'common.xsd']);
    console.log(`[AI-STUDIO] Loaded XSD schema library: ${library.events.length} events, ${library.conditions.length} conditions, ${library.actions.length} actions.`);
    return library;
  } catch (error: any) {
    console.warn(`[AI-STUDIO] XSD schema library unavailable: ${error.message || error}`);
    return createEmptySchemaLibrary(error.message || String(error));
  }
}

let schemaLibrary: SchemaLibrary = loadCurrentSchemaLibrary();
let schemaTemplatesByTag = new Map(schemaLibrary.templates.map(template => [template.xmlTag, template]));

function reloadSchemaLibrary(): SchemaLibrary {
  schemaLibrary = loadCurrentSchemaLibrary();
  schemaTemplatesByTag = new Map(schemaLibrary.templates.map(template => [template.xmlTag, template]));
  return schemaLibrary;
}

app.use(express.json({ limit: "5mb" }));

// Enable CORS only for this app's same-port localhost origins.
app.use((req, res, next) => {
  const origin = req.headers.origin;
  const allowedOrigins = new Set([
    `http://127.0.0.1:${PORT}`,
    `http://localhost:${PORT}`
  ]);
  if (origin && allowedOrigins.has(origin)) {
    res.header("Access-Control-Allow-Origin", origin);
  }
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization, x-ai-provider, x-custom-api-key");
  res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS, PUT, DELETE");
  if (req.method === "OPTIONS") {
    return res.sendStatus(200);
  }
  next();
});

// Middleware to verify the app session token for all /api/* routes.
function authMiddleware(req: express.Request, res: express.Response, next: express.NextFunction) {
  if (req.method === "GET" && req.path === "/agent/schema") {
    return next();
  }

  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ error: "Unauthorized: Missing token." });
  }
  
  const token = authHeader.substring(7);
  if (token !== STUDIO_API_TOKEN) {
    return res.status(401).json({ error: "Unauthorized: Invalid token." });
  }
  
  next();
}

app.use("/api", authMiddleware);

type CompiledFileManifest = Record<string, string>;

function buildWorkspaceFileManifest(workspaceInput: any): { modId: string; files: CompiledFileManifest } {
  const ws = sanitizeWorkspace(workspaceInput);
  const modId = toSafeModId(ws.name);
  const files: CompiledFileManifest = {};

  files["content.xml"] = generateContentXML(modId, ws);
  files["README.md"] = `# ${ws.name || modId}\n\nGenerated by X4:MD Studio.\n\nInstall location:\n\n\`\`\`\nX4 Foundations/extensions/${modId}/\n\`\`\`\n\nRuntime reload during development: save files, then run \`refreshmd\` in X4's debug command input.\n`;
  files[`md/${modId}.xml`] = generateMDXML(ws);

  if (ws.uiWidgets?.length) {
    files[`md_ui_layouts/${modId}_ui.xml`] = generateUIXML(ws);
  }

  for (const script of ws.aiScripts || []) {
    const fileName = script.name.endsWith(".xml") ? script.name : `${script.name}.xml`;
    files[`aiscripts/${fileName}`] = compileScriptToXML(script);
  }

  if (ws.wares?.length) {
    files["libraries/wares.xml"] = compileWaresXML(ws.wares);
  }
  if (ws.jobs?.length) {
    files["libraries/jobs.xml"] = compileJobsXML(ws.jobs);
  }

  for (const tFile of ws.tFiles || []) {
    files[`t/${tFile.fileName || `0001-L${tFile.languageId}.xml`}`] = compileTFileXML(tFile);
  }

  if (ws.xmlPatches?.length) {
    const patchesByFile: Record<string, any[]> = {};
    ws.xmlPatches.forEach((patch: any) => {
      const file = patch.targetFile || "libraries/ship_macros.xml";
      if (!patchesByFile[file]) {
        patchesByFile[file] = [];
      }
      patchesByFile[file].push(patch);
    });

    for (const [filePath, filePatches] of Object.entries(patchesByFile)) {
      files[filePath] = compileDiffDocument(filePatches, filePath);
    }
  }

  return { modId, files };
}

function summarizeWorkspaceDomains(ws: ModWorkspace) {
  return {
    nodes: ws.nodes?.length || 0,
    links: ws.links?.length || 0,
    uiWidgets: ws.uiWidgets?.length || 0,
    tFiles: ws.tFiles?.length || 0,
    aiScripts: ws.aiScripts?.length || 0,
    wares: ws.wares?.length || 0,
    jobs: ws.jobs?.length || 0,
    xmlPatches: ws.xmlPatches?.length || 0
  };
}

// Server-persisted active workspace (in-memory, preloaded with the Escort project)
const DEFAULT_WORKSPACE: ModWorkspace = {
  id: "workspace_default",
  name: "Player_Elite_Escort",
  version: "1.2.0",
  author: "EliteModder",
  description: "Automatically equips the user playership with heavy wing escorts on game entry.",
  nodes: [
    {
      id: "cue_0",
      type: "cue",
      label: "Mission Cue",
      xmlTag: "cue",
      x: 100,
      y: 100,
      properties: {
        name: "Escort_Trigger_Cue",
        instantiate: "true",
        namespace: "this",
        state: "active"
      },
      propertiesSchema: NODE_TEMPLATES[0].propertiesSchema,
      inputs: NODE_TEMPLATES[0].inputs,
      outputs: NODE_TEMPLATES[0].outputs
    },
    {
      id: "event_0",
      type: "event",
      label: "Event: Game Started",
      xmlTag: "event_cue_signalled",
      x: 100,
      y: 400,
      properties: { cue: "md.Setup.Start" },
      propertiesSchema: NODE_TEMPLATES[NODE_TEMPLATES.findIndex(t => t.xmlTag === 'event_cue_signalled')].propertiesSchema,
      inputs: NODE_TEMPLATES[NODE_TEMPLATES.findIndex(t => t.xmlTag === 'event_cue_signalled')].inputs,
      outputs: NODE_TEMPLATES[NODE_TEMPLATES.findIndex(t => t.xmlTag === 'event_cue_signalled')].outputs
    },
    {
      id: "action_0",
      type: "action",
      label: "Spawn Ship",
      xmlTag: "create_ship",
      x: 450,
      y: 150,
      properties: {
        name: "$MyHeavyEscort",
        macro: "ship_arg_s_fighter_01_a_macro (Elite Vanguard)",
        faction: "player",
        sector: "player.sector",
        coords: "0,500,-1000"
      },
      propertiesSchema: NODE_TEMPLATES[NODE_TEMPLATES.findIndex(t => t.xmlTag === 'create_ship')].propertiesSchema,
      inputs: NODE_TEMPLATES[NODE_TEMPLATES.findIndex(t => t.xmlTag === 'create_ship')].inputs,
      outputs: NODE_TEMPLATES[NODE_TEMPLATES.findIndex(t => t.xmlTag === 'create_ship')].outputs
    }
  ],
  links: [
    { id: "l0", sourceNodeId: "cue_0", sourcePortId: "out_cond", targetNodeId: "event_0", targetPortId: "in_cond" },
    { id: "l1", sourceNodeId: "cue_0", sourcePortId: "out_act", targetNodeId: "action_0", targetPortId: "in_act" }
  ],
  uiWidgets: [
    { id: "w_0", type: "window", x: 100, y: 100, w: 420, h: 300, label: "Escort Fleet Terminal", properties: {} },
    { id: "w_1", type: "header", x: 120, y: 140, w: 380, h: 40, label: "TACTICAL FLIGHT OPS", properties: {} },
    { id: "w_2", type: "progressbar", x: 120, y: 200, w: 380, h: 30, label: "Escort Integrity", properties: { value: 92, progressColor: "#00ccff" } }
  ],
  uiTheme: {
    backgroundColor: "#111827",
    borderColor: "#06b6d4",
    accentColor: "#0891b2",
    opacity: 0.9,
    showIcons: true
  }
};

let activeWorkspace: ModWorkspace = JSON.parse(JSON.stringify(DEFAULT_WORKSPACE));
// Track version counter to help with client-side merge prompts
let workspaceVersion = 1;

// -----------------------------------------------------
// Helper to call generateContent with retry and fallback model capability
// to handle temporary 503 Spikes in Demand / UNAVAILABLE errors.
// -----------------------------------------------------
async function generateContentWithRetry(ai: any, params: any, maxRetries = 2) {
  const modelsToTry = [params.model, "gemini-3.1-flash-lite", "gemini-flash-latest"];
  const modelsList = Array.from(new Set(modelsToTry.filter(Boolean)));
  
  let lastError: any = null;
  
  for (const modelName of modelsList) {
    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        console.log(`[AI-STUDIO] Trying generation on model: ${modelName} (attempt ${attempt}/${maxRetries})`);
        const response = await ai.models.generateContent({
          ...params,
          model: modelName,
        });
        return response;
      } catch (error: any) {
        lastError = error;
        const errMessage = error.message || "";
        const errString = JSON.stringify(error) || "";
        const is503 = errMessage.includes("503") || 
                      errMessage.toLowerCase().includes("unavailable") || 
                      errMessage.toLowerCase().includes("high demand") || 
                      errString.includes("503") || 
                      errString.toLowerCase().includes("unavailable") ||
                      errString.toLowerCase().includes("high demand");
                      
        console.error(`[AI-STUDIO] Error with model ${modelName} on attempt ${attempt}:`, error);
        
        if (is503) {
          if (attempt < maxRetries) {
            const delay = attempt * 1200;
            console.log(`[AI-STUDIO] Retrying in ${delay}ms...`);
            await new Promise((resolve) => setTimeout(resolve, delay));
            continue;
          } else {
            console.warn(`[AI-STUDIO] Model ${modelName} failed after max retries.`);
          }
        } else {
          // If we encounter a critical non-503 failure (e.g. incorrect parameter or permissions),
          // skip to trying the fallback model immediately.
          break;
        }
      }
    }
  }
  
  throw lastError || new Error("All model options and retries failed.");
}

// -----------------------------------------------------
// Unified Multi-Provider AI Endpoint Controller (Gemini, Claude, OpenAI)
// Plays direct native fetch proxy requests to protect backend secrets.
// -----------------------------------------------------
async function callMultiProviderAI(
  req: express.Request,
  systemInstruction: string,
  prompt: string,
  responseFormat: "json" | "text" = "text",
  jsonSchema?: any
): Promise<string> {
  const provider = (req.headers["x-ai-provider"] as string) || "gemini";
  const customKey = (req.headers["x-custom-api-key"] as string) || "";
  const model = (req.headers["x-ai-model"] as string) || "";
  const reasoning = (req.headers["x-ai-reasoning"] as string) || "none";

  if (provider === "claude") {
    const claudeKey = customKey || process.env.ANTHROPIC_API_KEY;
    if (!claudeKey) {
      throw new Error("Anthropic API key is not configured. Please supply your API Key in the AI Providers settings modal.");
    }

    const finalModel = model || "claude-3-5-sonnet-latest";
    let finalPrompt = prompt;
    if (responseFormat === "json") {
      finalPrompt = `${prompt}\n\nCRITICAL: Return ONLY a raw, fully valid JSON object fitting this schema specifications: ${JSON.stringify(jsonSchema || {})}. Do NOT wrap the JSON inside markdown blocks or include any extra conversational text! Only output valid JSON!`;
    }

    const bodyPayload: any = {
      model: finalModel,
      system: systemInstruction,
      messages: [
        { role: "user", content: finalPrompt }
      ]
    };

    // If user requested active thinking level, configure budget_tokens
    if (reasoning !== "none" && (finalModel.includes("3-7") || finalModel.includes("4-") || finalModel.includes("thinking") || reasoning === "extra_high" || reasoning === "high")) {
      let budget = 2048;
      if (reasoning === "low") budget = 1024;
      else if (reasoning === "medium") budget = 2048;
      else if (reasoning === "high") budget = 4096;
      else if (reasoning === "extra_high") budget = 8192;

      bodyPayload.thinking = {
        type: "enabled",
        budget_tokens: budget
      };
      bodyPayload.max_tokens = budget + 4000;
    } else {
      bodyPayload.max_tokens = 4000;
    }

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": claudeKey,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json"
      },
      body: JSON.stringify(bodyPayload)
    });

    const data: any = await response.json();
    if (!response.ok) {
      throw new Error(data?.error?.message || `Anthropic Claude API returned error code ${response.status}`);
    }

    let textOut = data?.content?.[0]?.text || "";
    // Clean codeblock wraps if returned
    if (textOut.trim().startsWith("```")) {
      textOut = textOut.replace(/^```[a-zA-Z]*\n/, "").replace(/\n```$/, "");
    }
    return textOut.trim();

  } else if (provider === "openai") {
    const openaiKey = customKey || process.env.OPENAI_API_KEY;
    if (!openaiKey) {
      throw new Error("OpenAI API key is not configured. Please supply your API Key in the AI Providers settings modal.");
    }

    const finalModel = model || "gpt-4o";
    let finalPrompt = prompt;
    if (responseFormat === "json") {
      finalPrompt = `${prompt}\n\nCRITICAL: Return ONLY a raw, fully valid JSON object fitting this schema specifications: ${JSON.stringify(jsonSchema || {})}. Do NOT wrap the JSON inside markdown blocks or include any extra conversational text! Only output valid JSON!`;
    }

    const bodyPayload: any = {
      model: finalModel,
      messages: [
        { role: "system", content: systemInstruction },
        { role: "user", content: finalPrompt }
      ],
      response_format: responseFormat === "json" ? { type: "json_object" } : undefined
    };

    // Custom reasoning levels for o-models / reasoning
    if (reasoning !== "none" && (finalModel.startsWith("o") || finalModel.includes("reasoning"))) {
      let effort: "low" | "medium" | "high" = "medium";
      if (reasoning === "low") effort = "low";
      else if (reasoning === "medium") effort = "medium";
      else if (reasoning === "high" || reasoning === "extra_high") effort = "high";

      bodyPayload.reasoning_effort = effort;
    }

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${openaiKey}`,
        "content-type": "application/json"
      },
      body: JSON.stringify(bodyPayload)
    });

    const data: any = await response.json();
    if (!response.ok) {
      throw new Error(data?.error?.message || `OpenAI API returned error code ${response.status}`);
    }

    let textOut = data?.choices?.[0]?.message?.content || "";
    // Clean codeblock wraps if returned
    if (textOut.trim().startsWith("```")) {
      textOut = textOut.replace(/^```[a-zA-Z]*\n/, "").replace(/\n```$/, "");
    }
    return textOut.trim();

  } else if (provider === "openrouter") {
    const openrouterKey = customKey || process.env.OPENROUTER_API_KEY || process.env.OPEN_ROUTER_API_KEY;
    if (!openrouterKey) {
      throw new Error("OpenRouter API key is not configured. Please supply your API Key in the AI Providers settings modal.");
    }

    const finalModel = model || "google/gemini-2.1-flash";
    let finalPrompt = prompt;
    if (responseFormat === "json") {
      finalPrompt = `${prompt}\n\nCRITICAL: Return ONLY a raw, fully valid JSON object fitting this schema specifications: ${JSON.stringify(jsonSchema || {})}. Do NOT wrap the JSON inside markdown blocks or include any extra conversational text! Only output valid JSON!`;
    }

    const bodyPayload: any = {
      model: finalModel,
      messages: [
        { role: "system", content: systemInstruction },
        { role: "user", content: finalPrompt }
      ],
      response_format: responseFormat === "json" ? { type: "json_object" } : undefined
    };

    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${openrouterKey}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "https://ai.studio/build",
        "X-Title": "AI Studio Build"
      },
      body: JSON.stringify(bodyPayload)
    });

    const data: any = await response.json();
    if (!response.ok) {
      throw new Error(data?.error?.message || `OpenRouter API returned error code ${response.status}`);
    }

    let textOut = data?.choices?.[0]?.message?.content || "";
    if (textOut.trim().startsWith("```")) {
      textOut = textOut.replace(/^```[a-zA-Z]*\n/, "").replace(/\n```$/, "");
    }
    return textOut.trim();

  } else {
    // Default to Google Gemini API (standard model schema)
    const geminiKey = customKey || process.env.GEMINI_API_KEY;
    if (!geminiKey || geminiKey === "MY_GEMINI_API_KEY") {
      throw new Error("Gemini API key is not configured. Please supply your API Key in the AI Providers settings modal to enable cognitive assistance.");
    }

    const finalModel = model || "gemini-3.5-flash";

    const ai = new GoogleGenAI({
      apiKey: geminiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });

    const config: any = {
      systemInstruction,
      temperature: responseFormat === "json" ? 0.3 : 0.7,
    };

    if (reasoning !== "none") {
      // Set thinking budget or custom instructions
      let extraInstructions = "";
      if (reasoning === "low") extraInstructions = "\n(Optimize for brief, straightforward, direct responses with light analysis)";
      else if (reasoning === "medium") extraInstructions = "\n(Employ steady logical step-by-step thinking processes for accuracy)";
      else if (reasoning === "high") extraInstructions = "\n(Utilize deep internal multi-step reasoning before outputting details)";
      else if (reasoning === "extra_high") extraInstructions = "\n(Maximize comprehensive logical thinking effort and address all latent edge cases)";
      
      config.systemInstruction = `${systemInstruction}${extraInstructions}`;
    }

    if (responseFormat === "json") {
      config.responseMimeType = "application/json";
      config.responseSchema = jsonSchema;
    }

    const response = await generateContentWithRetry(ai, {
      model: finalModel,
      contents: prompt,
      config
    });

    return response.text || "";
  }
}

// -----------------------------------------------------
// 1. ORIGINAL GEMINI CHAT CHOTBOT API
// -----------------------------------------------------
app.post("/api/gemini", async (req, res) => {
  const { prompt, currentWorkspace, diagnostics } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: "Missing prompt parameter." });
  }

  try {
    const systemInstruction = "You are an elite X4: Foundations XML & Mission Director MD scripting expert. Help the player write clean, functional scripts. Maximize brief and scan-friendly code blocks using markdown formatting. Avoid lengthy definitions, get straight to functional XML examples and tips.";
    
    let finalPrompt = prompt;
    if (currentWorkspace) {
      finalPrompt = `You are helping the player analyze, fix, or write script code within the context of their active visual node-graph workspace and list of active XML schema diagnostics.

[Active Workspace Context]:
- Name: "${currentWorkspace.name}"
- Description: "${currentWorkspace.description || "No description provided."}"
- Nodes: ${JSON.stringify(currentWorkspace.nodes?.map((n: any) => ({ id: n.id, label: n.label, type: n.type, xmlTag: n.xmlTag, properties: n.properties })) || [])}
- Links/Connections: ${JSON.stringify(currentWorkspace.links || [])}
- UI Widgets: ${JSON.stringify(currentWorkspace.uiWidgets || [])}

[Live XML Schema Diagnostics (Errors / Warnings)]:
${diagnostics && diagnostics.length > 0 ? JSON.stringify(diagnostics, null, 2) : "0 Errors, 0 Warnings. Everything currently compiles and validates successfully!"}

[User Query / Direct Instructions]:
"${prompt}"

Please respond accurately to the user query using the above active workspace state and diagnostics as key context. If they are asking you to fix a warning or error, analyze which node or property is violating rules and tell them exactly how they can adjust those parameters!`;
    }

    const responseText = await callMultiProviderAI(req, systemInstruction, finalPrompt, "text");
    return res.json({ text: responseText });
  } catch (error: any) {
    console.error("Multi-Provider chat routing error: ", error);
    return res.status(500).json({ error: error.message || "Failed to trigger AI compilation." });
  }
});

/**
 * POST /api/gemini/analyze
 * Analyzes the visual graph workspace and returns a structured, plain-English summary breakdown.
 */
app.post("/api/gemini/analyze", async (req, res) => {
  const { workspace } = req.body;
  if (!workspace) {
    return res.status(400).json({ error: "Missing workspace in request body." });
  }

  try {
    const systemInstruction = `You are a cognitive script compiler and narrative designer for X4: Foundations' Egosoft Mission Director (MD) codebase.
Your task is to analyze the provided visual graph workspace representing an X4 mod. Explain in plain English how the logic flows, what events are triggered, what actions are taken, and registry of any entities created (ships, stations, sounds, UI widgets, etc.).
Be highly precise and translate technical terms to clear logical human outcomes. Avoid overly technical jargon, make it friendly, descriptive, and clean. Ensure to outline safety warnings if any logical flaws exist (like disconnected nodes or triggers with no actions).`;

    const prompt = `Analyze this X4 Foundations ModWorkspace: ${JSON.stringify(workspace)}`;
    const schema = {
      type: Type.OBJECT,
      required: ["summary", "triggerCondition", "flowSteps", "entityRegistry", "tacticalInsights"],
      properties: {
        summary: {
          type: Type.STRING,
          description: "A high-level 1-2 sentence overview of what this script actually accomplishes in plain English."
        },
        triggerCondition: {
          type: Type.STRING,
          description: "Clear explanation of how the script triggers in the game (e.g. game start, entering slot, sector change, etc.)."
        },
        flowSteps: {
          type: Type.ARRAY,
          description: "Step-by-step logical progression of the cues and links in the node network. Detail the links / connections between nodes in clear sequential order.",
          items: {
            type: Type.OBJECT,
            required: ["nodeId", "nodeLabel", "xmlTag", "plainEnglishAction", "sequenceOrder"],
            properties: {
              nodeId: { type: Type.STRING },
              nodeLabel: { type: Type.STRING },
              xmlTag: { type: Type.STRING },
              plainEnglishAction: { type: Type.STRING, description: "A highly descriptive sentence explaining what this specific node does and what settings it uses." },
              sequenceOrder: { type: Type.INTEGER, description: "Sequential order of execution start from 1" }
            }
          }
        },
        entityRegistry: {
          type: Type.ARRAY,
          description: "List of all physical or auditory assets created/spawned or customized by this script, including HUD UI widgets designed.",
          items: {
            type: Type.OBJECT,
            required: ["name", "type", "detail"],
            properties: {
              name: { type: Type.STRING, description: "Variables name or reference, e.g. $MyHeavyEscort, UI Frame 1, Sound: alarm_red" },
              type: { type: Type.STRING, description: "e.g., Ship, Station, UI Widget, Sound, State" },
              detail: { type: Type.STRING, description: "Specification details, like macros, faction settings, dimensions, colors, or values." }
            }
          }
        },
        tacticalInsights: {
          type: Type.ARRAY,
          description: "3 highly valuable recommendations, tips, or potential logic safety bugs about this visual script layout.",
          items: {
            type: Type.STRING
          }
        }
      }
    };

    const textOutput = await callMultiProviderAI(req, systemInstruction, prompt, "json", schema);
    const analysisResult = JSON.parse(textOutput.trim());
    return res.json({ analysis: analysisResult });

  } catch (error: any) {
    console.error("AI script analysis request error: ", error);
    return res.status(500).json({ error: error.message || "Failed to analyze mod script using AI." });
  }
});

/**
 * POST /api/gemini/analyze-log
 * Analyzes copy-pasted or uploaded debug.log contents, matches errors, logs, or cue warnings
 * with the visual script workspace, and generates direct 1-click playtest auto-fixes.
 */
app.post("/api/gemini/analyze-log", async (req, res) => {
  const { workspace, logs } = req.body;
  if (!workspace || !logs) {
    return res.status(400).json({ error: "Missing workspace or logs in request body." });
  }

  try {
    const systemInstruction = `You are a legendary senior game engine compiler and Mission Director (MD) debugger for X4: Foundations (Egosoft).
Your job is to analyze the user's modding game logs (such as debug.log or custom terminal traces) in context with their visual node workspace.
You must find and correlate issues mentioned in the logs to the specific nodes in the workspace.
For each correlated issue, explain the cause in clear plain English, cite the effect on the game, recommend a detailed playbook action, and provide a 1-click JSON "autoFix" structure to update a node property in the editor when applicable.

Validation / Correlation Rules:
- Under 'affectedNodeId', specify the ID of the node that caused or is corresponding to the error (e.g., matching a cue name to the node's 'name' property, or a sound/ship action).
- If 'autoFix' is generated, set type: 'update_node_property', nodeId to the ID of that node, propertyKey to the property key (like 'instantiate', 'faction', 'macro', etc.), and propertyValue to the corrected value.
- If no node perfectly matches, or it's a general game load log, leave affectedNodeId empty and omit the autoFix field.
- Be supportive, knowledgeable, and provide awesome expert playtester tips.`;

    const prompt = `Here is the current visual workspace:
${JSON.stringify({
  name: workspace.name,
  description: workspace.description,
  nodes: workspace.nodes.map((n: any) => ({ id: n.id, type: n.type, label: n.label, properties: n.properties, xmlTag: n.xmlTag })),
  links: workspace.links
})}

Here is the log segment uploaded by the user / playtester:
-----
${logs}
-----

Analyze this trace and return the structured issues diagnostics and suggestions.`;

    const schema = {
      type: Type.OBJECT,
      required: ["parsedLogsCount", "issues", "summaryOfGameMDReload"],
      properties: {
        parsedLogsCount: {
          type: Type.INTEGER,
          description: "Estimated number of distinct MD script errors/warnings parsed from logs"
        },
        summaryOfGameMDReload: {
          type: Type.STRING,
          description: "Brief human diagnosis summarizing the current playtest session reload state in X4."
        },
        issues: {
          type: Type.ARRAY,
          description: "Array of distinct warning/error issues found with actionable solutions.",
          items: {
            type: Type.OBJECT,
            required: ["id", "severity", "title", "errorLogSnippet", "explanation", "impact", "suggestedAction"],
            properties: {
              id: { type: Type.STRING, description: "Unique ID for identifying issue e.g. err_1" },
              severity: { type: Type.STRING, description: "Must be 'error' or 'warning'" },
              title: { type: Type.STRING, description: "Short descriptive title of the issue" },
              errorLogSnippet: { type: Type.STRING, description: "The exact line or relevant segment from user's logs" },
              explanation: { type: Type.STRING, description: "Why the Egosoft engine threw this warning/error" },
              impact: { type: Type.STRING, description: "How this impacts the gameplay experience or script execution" },
              suggestedAction: { type: Type.STRING, description: "Clear instructions of how the player should fix this manually inside or outside" },
              affectedNodeId: { type: Type.STRING, description: "Optional. The exact node ID from the workspace suffering from this issue." },
              autoFix: {
                type: Type.OBJECT,
                description: "Optional. Provide a 1-click auto-repair payload for the editor if applicable.",
                properties: {
                  type: { type: Type.STRING, description: "Must be 'update_node_property'" },
                  nodeId: { type: Type.STRING },
                  propertyKey: { type: Type.STRING, description: "Name of property to change on node" },
                  propertyValue: { type: Type.STRING, description: "The new corrected value for property" }
                }
              }
            }
          }
        }
      }
    };

    const textOutput = await callMultiProviderAI(req, systemInstruction, prompt, "json", schema);
    const parsedOutput = JSON.parse(textOutput.trim());
    return res.json({ analysis: parsedOutput });

  } catch (error: any) {
    console.error("AI log analysis error: ", error);
    return res.status(500).json({ error: error.message || "Failed to analyze X4 reload logs via AI compiler." });
  }
});


// -----------------------------------------------------
// 2. EXTERNAL AI AGENT DEVELOPMENT API ENDPOINTS
// -----------------------------------------------------

/**
 * GET /api/agent/schema
 * Exposes core constants, valid selection macro values, structural boundaries, and base templates.
 * Extremely helpful for AI agents to understand exactly what values are valid before making updates.
 */
app.get("/api/agent/schema", (req, res) => {
  const currentConfig = readXsdConfig();
  const resolvedConfig = resolveXsdConfig();
  return res.json({
    api_version: "2026-06-10.agent.v2",
    description: "X4 Foundations Mod Studio external agent contract. Use this to inspect supported workspace domains, valid values, compile outputs, and protected API routes before modifying the studio.",
    auth: {
      read_only_schema_is_public: true,
      protected_routes: "Every /api route except GET /api/agent/schema requires Authorization: Bearer <token>.",
      token_sources_for_local_agents: [
        "Read process.env.STUDIO_API_TOKEN when the server was started with one.",
        "Otherwise read the gitignored .studio-api-token file in the project root.",
        "The browser app receives the same token via injected window.__STUDIO_API_TOKEN__."
      ],
      curl_header: "Authorization: Bearer $(Get-Content .studio-api-token)"
    },
    workspace_contract: {
      required_root_fields: ["id", "name", "version", "author", "description", "nodes", "links", "uiWidgets", "uiTheme"],
      optional_domain_fields: ["tFiles", "aiScripts", "wares", "jobs", "xmlPatches"],
      domains: {
        mission_director: {
          fields: ["nodes", "links"],
          output: "md/<modId>.xml",
          node_types: ["cue", "event", "condition", "action", "variable", "comment"],
          link_ports: {
            cue_conditions: "cue.out_cond -> event_or_condition.in_cond",
            cue_actions: "cue.out_act -> first_action.in_act",
            action_chain: "action.out_next -> next_action.in_act",
            child_cues: "cue.out_sub -> child_cue.in_flow"
          }
        },
        ui_layout: {
          fields: ["uiWidgets", "uiTheme"],
          output: "md_ui_layouts/<modId>_ui.xml",
          widget_types: ["window", "table", "button", "text", "progressbar", "dropdown", "header", "input", "chat"],
          theme_fields: ["backgroundColor", "borderColor", "accentColor", "opacity", "showIcons"]
        },
        translations: {
          field: "tFiles",
          output: "t/<fileName>",
          shape: {
            languageId: "string, e.g. 44",
            fileName: "string, e.g. 0001-L044.xml",
            pages: [{ id: "string", title: "optional string", items: [{ id: "string", value: "string", description: "optional string" }] }]
          }
        },
        ai_scripts: {
          field: "aiScripts",
          output: "aiscripts/<script.name>.xml",
          action_commands: ["move_to", "flee", "shoot", "dock_at", "wait", "find_objects", "custom_xml"],
          param_types: ["object", "number", "boolean", "ware", "faction"],
          attention_levels: ["high", "low"]
        },
        libraries: {
          fields: ["wares", "jobs"],
          outputs: ["libraries/wares.xml", "libraries/jobs.xml"],
          ware_transport_types: ["container", "liquid", "solid", "energy"],
          job_ship_classes: ["fighter", "corvette", "destroyer", "carrier", "freighter"]
        },
        xml_patches: {
          field: "xmlPatches",
          output: "<patch.targetFile>",
          actions: ["add", "replace", "remove"],
          common_targets: ["libraries/ship_macros.xml", "libraries/sound_library.xml", "libraries/wares.xml", "libraries/jobs.xml"]
        },
        package_manifest: {
          always_outputs: ["content.xml", "README.md", "md/<modId>.xml"],
          conditional_outputs: ["md_ui_layouts/<modId>_ui.xml", "aiscripts/*.xml", "libraries/wares.xml", "libraries/jobs.xml", "t/*.xml", "<xmlPatch.targetFile>"]
        }
      },
      minimal_workspace: sanitizeWorkspace({ name: "My_AI_Mod", nodes: [], links: [], uiWidgets: [] })
    },
    endpoints: [
      {
        method: "GET",
        path: "/api/agent/schema",
        auth: false,
        purpose: "Fetch this agent contract, valid constants, schema templates, endpoint catalog, and workspace domain descriptions."
      },
      {
        method: "GET",
        path: "/api/agent/workspace",
        auth: true,
        purpose: "Read the active studio workspace plus version counter."
      },
      {
        method: "POST",
        path: "/api/agent/workspace",
        auth: true,
        body: { workspace: "ModWorkspace" },
        purpose: "Replace the active studio workspace and bump the version if changed."
      },
      {
        method: "POST",
        path: "/api/agent/compile",
        auth: true,
        body: { workspace: "optional ModWorkspace; defaults to active workspace" },
        purpose: "Compile every supported workspace domain into an in-memory file manifest without writing to disk."
      },
      {
        method: "POST",
        path: "/api/agent/package",
        auth: true,
        body: { workspace: "optional ModWorkspace; defaults to active workspace" },
        purpose: "Alias of compile for agents that want a package/file-manifest vocabulary."
      },
      {
        method: "POST",
        path: "/api/agent/deploy",
        auth: true,
        body: { workspace: "optional ModWorkspace; defaults to active workspace" },
        purpose: "Compile and write the package into configured Mod Workspace and/or X4 game extensions paths."
      },
      {
        method: "POST",
        path: "/api/agent/generate",
        auth: true,
        body: { prompt: "string", currentWorkspace: "optional ModWorkspace", diagnostics: "optional XMLDiagnostic[]" },
        purpose: "Ask the server-side AI provider to generate/edit a workspace. Current implementation mainly edits MD graph and UI domains while preserving other existing domains."
      },
      {
        method: "GET",
        path: "/api/schema/library",
        auth: true,
        purpose: "Read the loaded XSD-derived MD schema library."
      },
      {
        method: "GET",
        path: "/api/schema/config",
        auth: true,
        purpose: "Read configured X4 game path, mod workspace path, filesystem path, and XSD schema path."
      },
      {
        method: "POST",
        path: "/api/schema/config",
        auth: true,
        purpose: "Update directory settings and reload md.xsd/common.xsd."
      },
      {
        method: "GET",
        path: "/api/fs/list",
        auth: true,
        purpose: "List configured filesystem/mod workspace root."
      },
      {
        method: "GET",
        path: "/api/fs/read?path=<relativePath>",
        auth: true,
        purpose: "Read a file under the configured filesystem/mod workspace root."
      },
      {
        method: "POST",
        path: "/api/fs/write",
        auth: true,
        body: { path: "relative path under configured root", content: "string" },
        purpose: "Write a file under the configured filesystem/mod workspace root."
      },
      {
        method: "POST",
        path: "/api/fs/create",
        auth: true,
        body: { name: "relative name", type: "directory or file" },
        purpose: "Create a file or directory under the configured filesystem/mod workspace root."
      },
      {
        method: "GET",
        path: "/api/fs/snapshots?modId=<modId>",
        auth: true,
        purpose: "List package snapshots for a compiled mod."
      },
      {
        method: "POST",
        path: "/api/fs/restore-snapshot",
        auth: true,
        body: { modId: "string", snapshotName: "string" },
        purpose: "Restore a snapshot into the active server workspace."
      },
      {
        method: "POST",
        path: "/api/github/*",
        auth: true,
        purpose: "GitHub load, push, create, device-flow, and commits endpoints used by the SOURCE panel."
      }
    ],
    current_state: {
      workspace_version: workspaceVersion,
      active_workspace_domains: summarizeWorkspaceDomains(activeWorkspace),
      config: {
        has_x4_game_path: Boolean(currentConfig.x4GamePath),
        has_mod_workspace_path: Boolean(currentConfig.modWorkspacePath),
        has_filesystem_path: Boolean(currentConfig.filesystemPath),
        has_xsd_schema_path: Boolean(currentConfig.xsdSchemaPath),
        resolved_md_xsd: resolvedConfig.mdExists,
        resolved_common_xsd: resolvedConfig.commonExists
      }
    },
    constants: {
      factions: X4_FACTIONS,
      ship_macros: X4_SHIP_MACROS,
      station_macros: X4_STATION_MACROS,
      sound_effects: X4_SOUND_EFFECTS,
    },
    node_templates: NODE_TEMPLATES,
    schema_library_loaded: schemaLibrary.loaded,
    schema_counts: {
      events: schemaLibrary.events.length,
      conditions: schemaLibrary.conditions.length,
      actions: schemaLibrary.actions.length,
      control_flow: schemaLibrary.controlFlow.length,
    },
    schema_node_templates: schemaLibrary.templates,
    presets_list: Object.keys(PRESETS).map(key => ({
      id: key,
      name: PRESETS[key].name,
      desc: PRESETS[key].desc
    })),
    compile_response_shape: {
      success: "boolean",
      modId: "safe extension folder id",
      files: "Record<relativePath,string> containing every generated package file",
      legacy_files: {
        mission_director_xml: "same content as files['md/<modId>.xml']",
        ui_layout_xml: "same content as files['md_ui_layouts/<modId>_ui.xml'] when UI widgets exist"
      },
      diagnostics: "validateModWorkspace + validatePackageReadiness results",
      file_count: "number"
    }
  });
});

app.get("/api/schema/library", (req, res) => {
  return res.json(schemaLibrary);
});

app.get("/api/schema/config", (req, res) => {
  try {
    return res.json({
      config: readXsdConfig(),
      resolved: resolveXsdConfig(),
      schema_counts: {
        events: schemaLibrary.events.length,
        conditions: schemaLibrary.conditions.length,
        actions: schemaLibrary.actions.length,
        control_flow: schemaLibrary.controlFlow.length,
      },
      loaded: schemaLibrary.loaded,
      error: schemaLibrary.error
    });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to read schema config." });
  }
});

app.post("/api/schema/config", (req, res) => {
  try {
    const schemaDir = String(req.body?.schemaDir || '').trim();
    const gamePath = String(req.body?.x4GamePath || '').trim();
    const modWorkspacePath = req.body?.modWorkspacePath !== undefined ? String(req.body.modWorkspacePath || '').trim() : undefined;
    const filesystemPath = req.body?.filesystemPath !== undefined ? String(req.body.filesystemPath || '').trim() : undefined;

    if (!schemaDir) {
      return res.status(400).json({ error: "Missing required schemaDir." });
    }

    const nextConfig = {
      ...readXsdConfig(),
      ...(gamePath ? { x4GamePath: gamePath } : {}),
      ...(modWorkspacePath !== undefined ? { modWorkspacePath } : {}),
      ...(filesystemPath !== undefined ? { filesystemPath } : {}),
      xsdSchemaPath: schemaDir,
      schemaFiles: ['md.xsd', 'common.xsd']
    };
    const resolved = resolveXsdConfig(nextConfig);
    if (!resolved.mdExists || !resolved.commonExists) {
      return res.status(400).json({
        error: "Schema directory must contain both md.xsd and common.xsd.",
        resolved
      });
    }

    writeXsdConfig(nextConfig);
    const library = reloadSchemaLibrary();
    return res.json({
      success: library.loaded,
      config: nextConfig,
      resolved: resolveXsdConfig(nextConfig),
      schema_counts: {
        events: library.events.length,
        conditions: library.conditions.length,
        actions: library.actions.length,
        control_flow: library.controlFlow.length,
      },
      loaded: library.loaded,
      error: library.error
    });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to update schema config." });
  }
});

// Helper for scanning filesystem recursively
function scanDirectory(dir: string, baseDir: string): any[] {
  const items: any[] = [];
  try {
    if (!fs.existsSync(dir)) return [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relativePath = path.relative(baseDir, fullPath).replace(/\\/g, '/');
      if (entry.name.startsWith('.') && entry.name !== '.snapshots') {
        continue;
      }
      if (entry.name === 'node_modules' || entry.name === 'dist') {
        continue;
      }
      if (entry.isDirectory()) {
        items.push({
          name: entry.name,
          kind: 'directory',
          path: relativePath,
          children: scanDirectory(fullPath, baseDir)
        });
      } else {
        items.push({
          name: entry.name,
          kind: 'file',
          path: relativePath
        });
      }
    }
  } catch (err) {
    console.warn(`Error scanning directory ${dir}:`, err);
  }
  
  return items.sort((a, b) => {
    if (a.kind !== b.kind) {
      return a.kind === 'directory' ? -1 : 1;
    }
    return a.name.localeCompare(b.name);
  });
}

// Server Filesystem list endpoint
app.get("/api/fs/list", (req, res) => {
  try {
    const resolved = resolveXsdConfig();
    const rootPath = resolved.filesystemPath || resolved.modWorkspacePath;
    if (!rootPath) {
      return res.json([]);
    }
    if (!fs.existsSync(rootPath)) {
      return res.json([]);
    }
    const tree = scanDirectory(rootPath, rootPath);
    return res.json(tree);
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to list filesystem." });
  }
});

// Server Filesystem read endpoint
app.get("/api/fs/read", (req, res) => {
  try {
    const relativePath = String(req.query.path || '').trim();
    if (!relativePath) {
      return res.status(400).json({ error: "Missing path parameter." });
    }
    const resolved = resolveXsdConfig();
    const rootPath = resolved.filesystemPath || resolved.modWorkspacePath;
    if (!rootPath) {
      return res.status(400).json({ error: "No filesystem/workspace path configured." });
    }
    
    const safePath = path.resolve(rootPath, relativePath);
    if (!safePath.startsWith(path.resolve(rootPath))) {
      return res.status(403).json({ error: "Forbidden: Directory traversal detected." });
    }
    
    if (!fs.existsSync(safePath)) {
      return res.status(404).json({ error: "File not found." });
    }
    
    const content = fs.readFileSync(safePath, 'utf8');
    return res.json({ content });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to read file." });
  }
});

// Server Filesystem write endpoint
app.post("/api/fs/write", (req, res) => {
  try {
    const relativePath = String(req.body?.path || '').trim();
    const content = req.body?.content ?? '';
    if (!relativePath) {
      return res.status(400).json({ error: "Missing path parameter." });
    }
    const resolved = resolveXsdConfig();
    const rootPath = resolved.filesystemPath || resolved.modWorkspacePath;
    if (!rootPath) {
      return res.status(400).json({ error: "No filesystem/workspace path configured." });
    }
    
    const safePath = path.resolve(rootPath, relativePath);
    if (!safePath.startsWith(path.resolve(rootPath))) {
      return res.status(403).json({ error: "Forbidden: Directory traversal detected." });
    }
    
    const dir = path.dirname(safePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    
    fs.writeFileSync(safePath, content, 'utf8');
    return res.json({ success: true });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to write file." });
  }
});

// Server Filesystem create endpoint
app.post("/api/fs/create", (req, res) => {
  try {
    const { name, type } = req.body;
    if (!name) {
      return res.status(400).json({ error: "Missing name parameter." });
    }
    const cleanName = name.replace(/[^a-zA-Z0-9_.-]/g, '_');
    const resolved = resolveXsdConfig();
    const rootPath = resolved.filesystemPath || resolved.modWorkspacePath;
    if (!rootPath) {
      return res.status(400).json({ error: "No filesystem/workspace path configured." });
    }
    
    const safePath = path.resolve(rootPath, cleanName);
    if (!safePath.startsWith(path.resolve(rootPath))) {
      return res.status(403).json({ error: "Forbidden: Directory traversal detected." });
    }
    
    if (fs.existsSync(safePath)) {
      return res.status(400).json({ error: "Target already exists." });
    }
    
    if (type === 'directory') {
      fs.mkdirSync(safePath, { recursive: true });
    } else {
      const dir = path.dirname(safePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      fs.writeFileSync(safePath, '', 'utf8');
    }
    
    return res.json({ success: true, path: cleanName });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to create resource." });
  }
});

// Server Filesystem snapshots list endpoint
app.get("/api/fs/snapshots", (req, res) => {
  try {
    const modId = String(req.query.modId || '').trim();
    if (!modId) {
      return res.status(400).json({ error: "Missing modId parameter." });
    }
    const resolved = resolveXsdConfig();
    const modWorkspacePath = resolved.modWorkspacePath;
    if (!modWorkspacePath) {
      return res.json([]);
    }
    const snapDir = path.join(modWorkspacePath, modId, '.snapshots');
    if (!fs.existsSync(snapDir)) {
      return res.json([]);
    }
    const files = fs.readdirSync(snapDir).filter(name => name.startsWith('snapshot_') && name.endsWith('.json'));
    const list = files.map(file => {
      try {
        const content = fs.readFileSync(path.join(snapDir, file), 'utf8');
        const parsed = JSON.parse(content);
        return {
          name: file,
          savedAt: parsed.savedAt || new Date().toISOString()
        };
      } catch (e) {
        return {
          name: file,
          savedAt: new Date().toISOString()
        };
      }
    });
    list.sort((a, b) => b.name.localeCompare(a.name));
    return res.json(list);
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to list snapshots." });
  }
});

// Server Filesystem restore snapshot endpoint
app.post("/api/fs/restore-snapshot", (req, res) => {
  try {
    const { modId, snapshotName } = req.body;
    if (!modId || !snapshotName) {
      return res.status(400).json({ error: "Missing modId or snapshotName parameter." });
    }
    const resolved = resolveXsdConfig();
    const modWorkspacePath = resolved.modWorkspacePath;
    if (!modWorkspacePath) {
      return res.status(400).json({ error: "No mod workspace path configured." });
    }
    const snapFile = path.join(modWorkspacePath, modId, '.snapshots', snapshotName);
    if (!fs.existsSync(snapFile)) {
      return res.status(404).json({ error: "Snapshot not found." });
    }
    const content = fs.readFileSync(snapFile, 'utf8');
    const parsed = JSON.parse(content);
    if (!parsed.workspace) {
      return res.status(400).json({ error: "Invalid snapshot format." });
    }
    
    activeWorkspace = parsed.workspace;
    workspaceVersion++;
    
    return res.json({ success: true, workspace: activeWorkspace });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to restore snapshot." });
  }
});

app.get("/api/schema/element/:tag", (req, res) => {
  const tag = req.params.tag;
  const element = [
    ...schemaLibrary.events,
    ...schemaLibrary.conditions,
    ...schemaLibrary.actions,
    ...schemaLibrary.controlFlow
  ].find(item => item.tag === tag);

  if (!element) {
    return res.status(404).json({ error: `Schema element not found: ${tag}` });
  }
  return res.json(element);
});

/**
 * GET /api/agent/workspace
 * Retrieves the currently active, synchronized workspace state.
 */
app.get("/api/agent/workspace", (req, res) => {
  return res.json({
    workspace: activeWorkspace,
    version: workspaceVersion,
    lastUpdated: new Date().toISOString()
  });
});

/**
 * POST /api/agent/workspace
 * Updates the currently active workspace state and bumps the revision version.
 */
app.post("/api/agent/workspace", (req, res) => {
  const { workspace } = req.body;
  if (!workspace) {
    return res.status(400).json({ error: "Missing required 'workspace' body parameter." });
  }
  const nextWorkspace = sanitizeWorkspace(workspace);

  // Set the workspace and bump version only if it changed
  const isDifferent = JSON.stringify(nextWorkspace) !== JSON.stringify(activeWorkspace);
  if (isDifferent) {
    activeWorkspace = nextWorkspace;
    workspaceVersion++;
  }

  return res.json({
    success: true,
    message: isDifferent ? "Workspace successfully updated on the studio, bumping version." : "Workspace already in sync.",
    version: workspaceVersion,
    workspace: activeWorkspace
  });
});

function compileWorkspaceToFolder(ws: any, rootPath: string, mode: 'candy' | 'store'): string {
  const modId = toSafeModId(ws.name);
  const targetPath = mode === 'store' ? path.join(rootPath, modId) : rootPath;

  if (mode === 'store') {
    if (fs.existsSync(targetPath)) {
      fs.rmSync(targetPath, { recursive: true, force: true });
    }
  }
  if (!fs.existsSync(targetPath)) {
    fs.mkdirSync(targetPath, { recursive: true });
  }

  // 1. content.xml
  const contentXml = generateContentXML(modId, ws);
  fs.writeFileSync(path.join(targetPath, 'content.xml'), contentXml);

  // 2. README.md
  fs.writeFileSync(path.join(targetPath, 'README.md'), `# ${ws.name || modId}\n\nGenerated by X4:MD Studio.\n`);

  // 3. md/<modId>.xml
  const mdXml = generateMDXML(ws);
  const mdDir = path.join(targetPath, 'md');
  fs.mkdirSync(mdDir, { recursive: true });
  fs.writeFileSync(path.join(mdDir, `${modId}.xml`), mdXml);

  // 4. UI
  if (ws.uiWidgets?.length) {
    const uiDir = path.join(targetPath, 'md_ui_layouts');
    fs.mkdirSync(uiDir, { recursive: true });
    const uiXml = generateUIXML(ws);
    fs.writeFileSync(path.join(uiDir, `${modId}_ui.xml`), uiXml);
  }

  // 5. AIScripts
  if (ws.aiScripts?.length) {
    const aiDir = path.join(targetPath, 'aiscripts');
    fs.mkdirSync(aiDir, { recursive: true });
    for (const script of ws.aiScripts) {
      const fileName = script.name.endsWith('.xml') ? script.name : `${script.name}.xml`;
      fs.writeFileSync(path.join(aiDir, fileName), compileScriptToXML(script));
    }
  }

  // 6. Wares and Jobs
  if (ws.wares?.length || ws.jobs?.length) {
    const libDir = path.join(targetPath, 'libraries');
    fs.mkdirSync(libDir, { recursive: true });
    if (ws.wares?.length) {
      fs.writeFileSync(path.join(libDir, 'wares.xml'), compileWaresXML(ws.wares));
    }
    if (ws.jobs?.length) {
      fs.writeFileSync(path.join(libDir, 'jobs.xml'), compileJobsXML(ws.jobs));
    }
  }

  // 7. Translations
  if (ws.tFiles?.length) {
    const tDir = path.join(targetPath, 't');
    fs.mkdirSync(tDir, { recursive: true });
    for (const tFile of ws.tFiles) {
      const fileName = tFile.fileName || `0001-L${tFile.languageId}.xml`;
      fs.writeFileSync(path.join(tDir, fileName), compileTFileXML(tFile));
    }
  }

  // 8. XML diff patches
  if (ws.xmlPatches?.length) {
    const patchesByFile: Record<string, any[]> = {};
    ws.xmlPatches.forEach((patch: any) => {
      const file = patch.targetFile || 'libraries/ship_macros.xml';
      if (!patchesByFile[file]) {
        patchesByFile[file] = [];
      }
      patchesByFile[file].push(patch);
    });

    for (const [filePath, filePatches] of Object.entries(patchesByFile)) {
      const targetFilePath = path.join(targetPath, filePath);
      const targetDir = path.dirname(targetFilePath);
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }
      fs.writeFileSync(targetFilePath, compileDiffDocument(filePatches, filePath));
    }
  }

  // Snapshots
  try {
    const snapDir = path.join(targetPath, '.snapshots');
    if (!fs.existsSync(snapDir)) {
      fs.mkdirSync(snapDir, { recursive: true });
    }
    const stamp = new Date().toISOString().replace(/[:.]/g, '-');
    fs.writeFileSync(
      path.join(snapDir, `snapshot_${stamp}.json`),
      JSON.stringify({ savedAt: new Date().toISOString(), name: ws.name, workspace: ws }, null, 2),
      'utf8'
    );
    const names = fs.readdirSync(snapDir).filter(name => name.startsWith('snapshot_') && name.endsWith('.json'));
    names.sort();
    const MAX_SNAPSHOTS = 30;
    for (let i = 0; i < names.length - MAX_SNAPSHOTS; i++) {
      fs.unlinkSync(path.join(snapDir, names[i]));
    }
  } catch (err) {
    console.warn('Snapshot write failed (non-fatal):', err);
  }

  return targetPath;
}

/**
 * POST /api/agent/deploy
 * Compiles and deploys the workspace directly into the configured X4 Extensions directory.
 */
app.post("/api/agent/deploy", (req, res) => {
  const ws = sanitizeWorkspace(req.body.workspace || activeWorkspace);
  try {
    const resolved = resolveXsdConfig();
    const modWorkspacePath = resolved.modWorkspacePath;
    const x4GamePath = resolved.x4GamePath;
    
    if (!modWorkspacePath && !x4GamePath) {
      return res.status(400).json({
        success: false,
        error: "Neither Mod Workspace Folder nor X4 Game Installation are configured."
      });
    }

    const modId = toSafeModId(ws.name);
    let stagingPath = '';
    let deployedPath = '';

    // 1. Compile to Mod Workspace Path (Staging) if configured
    if (modWorkspacePath) {
      if (!fs.existsSync(modWorkspacePath)) {
        fs.mkdirSync(modWorkspacePath, { recursive: true });
      }
      stagingPath = compileWorkspaceToFolder(ws, modWorkspacePath, 'store');
    }

    // 2. Compile and deploy to Game Extensions Path if configured
    if (x4GamePath) {
      if (fs.existsSync(x4GamePath)) {
        const extensionsPath = path.join(x4GamePath, 'extensions');
        if (!fs.existsSync(extensionsPath)) {
          fs.mkdirSync(extensionsPath, { recursive: true });
        }
        deployedPath = compileWorkspaceToFolder(ws, extensionsPath, 'store');
      } else {
        console.warn(`Configured X4 Game Installation path "${x4GamePath}" does not exist.`);
      }
    }

    let message = '';
    if (stagingPath && deployedPath) {
      message = `Successfully compiled to staging workspace AND deployed to game extensions: ${deployedPath}`;
    } else if (stagingPath) {
      message = `Successfully compiled to staging workspace: ${stagingPath}`;
    } else if (deployedPath) {
      message = `Successfully deployed to game extensions: ${deployedPath}`;
    }

    return res.json({
      success: true,
      message,
      deployedPath: deployedPath || stagingPath
    });
  } catch (error: any) {
    return res.status(500).json({
      success: false,
      error: error.message || "Failed to compile/deploy mod."
    });
  }
});

/**
 * POST /api/agent/compile
 * Compiles a submitted workspace JSON body on-the-fly and runs the Mod Studio XML validator check.
 */
app.post("/api/agent/compile", (req, res) => {
  const ws = sanitizeWorkspace(req.body.workspace || activeWorkspace);
  try {
    const { modId, files } = buildWorkspaceFileManifest(ws);
    const mdPath = `md/${modId}.xml`;
    const uiPath = `md_ui_layouts/${modId}_ui.xml`;
    const diagnostics = [
      ...validateModWorkspace(ws, files[mdPath] || generateMDXML(ws)),
      ...validatePackageReadiness(ws)
    ];

    return res.json({
      success: true,
      modId,
      file_count: Object.keys(files).length,
      files: {
        ...files,
        mission_director_xml: files[mdPath],
        ui_layout_xml: files[uiPath] || ""
      },
      legacy_files: {
        mission_director_xml: files[mdPath],
        ui_layout_xml: files[uiPath] || ""
      },
      diagnostics
    });
  } catch (error: any) {
    return res.status(500).json({
      success: false,
      error: error.message || "Failed to compile workspace schema to XML."
    });
  }
});

/**
 * POST /api/agent/package
 * Agent-friendly alias for compile that returns the complete package file manifest.
 */
app.post("/api/agent/package", (req, res) => {
  const ws = sanitizeWorkspace(req.body.workspace || activeWorkspace);
  try {
    const { modId, files } = buildWorkspaceFileManifest(ws);
    const mdPath = `md/${modId}.xml`;
    const diagnostics = [
      ...validateModWorkspace(ws, files[mdPath] || generateMDXML(ws)),
      ...validatePackageReadiness(ws)
    ];

    return res.json({
      success: true,
      modId,
      file_count: Object.keys(files).length,
      files,
      diagnostics
    });
  } catch (error: any) {
    return res.status(500).json({
      success: false,
      error: error.message || "Failed to package workspace schema to file manifest."
    });
  }
});

function populateNodeMetadata(nodes: any[]): any[] {
  if (!nodes || !Array.isArray(nodes)) return [];
  return nodes.map(node => {
    // Attempt to match by xmlTag
    let template = NODE_TEMPLATES.find(t => t.xmlTag === node.xmlTag);
    if (!template) {
      template = schemaTemplatesByTag.get(node.xmlTag);
    }
    // Fallback search by type
    if (!template) {
      template = NODE_TEMPLATES.find(t => t.type === node.type);
    }
    // Deep fallback to first template
    if (!template) {
      template = NODE_TEMPLATES[0];
    }
    
    return {
      id: node.id || `node_${Math.random().toString(36).substring(2, 9)}`,
      type: node.type || template.type,
      label: node.label || template.label,
      xmlTag: node.xmlTag || template.xmlTag,
      x: typeof node.x === 'number' ? node.x : Math.floor(Math.random() * 500) + 100,
      y: typeof node.y === 'number' ? node.y : Math.floor(Math.random() * 400) + 100,
      properties: { ...template.properties, ...node.properties },
      propertiesSchema: template.propertiesSchema,
      inputs: template.inputs,
      outputs: template.outputs,
      comment: node.comment || ""
    };
  });
}

/**
 * POST /api/agent/generate
 * Prompts the built-in Gemini language model to map a natural language instruction directly
 * into a highly complex, logical ModWorkspace structured JSON value.
 */
app.post("/api/agent/generate", async (req, res) => {
  const { prompt, currentWorkspace, diagnostics } = req.body;
  if (!prompt) {
    return res.status(400).json({ error: "Missing 'prompt' body parameter." });
  }
  const baseWorkspace = sanitizeWorkspace(currentWorkspace || activeWorkspace);

  try {
    console.log(`[AI-STUDIO] Starting Phased Cognitive Prompt Interpretation Workflow...`);
    
    // --- PHASE 1: CORE NODE BLUEPRINT INTERPRETER ---
    console.log(`[AI-STUDIO] [Phase 1/4] Interrogating Intent & Node Visual Setup...`);
    const phase1System = `You are Phase 1 of a visual workspace translator. Design or edit ONLY the workspace metadata (name, version, author, description) and the raw "nodes" array based on the user's raw prompt.
Do not worry about linkages / links or uiWidgets. 
Focus on allocating:
1. Cue nodes (type="cue", xmlTag="cue") representing mission cues.
2. Event/Condition nodes (type="event" or type="condition") representing triggers/checks. Available xmlTags: "event_cue_signalled", "event_object_destroyed", "event_object_changed_sector", "check_value", "custom_event", "custom_condition".
3. Action nodes (type="action") representing actions. Available xmlTags: "create_ship", "reward_player", "play_sound", "show_help", "create_station", "custom_xml".

Ensure each node has a unique 'id' (e.g., 'cue_0', 'event_0', 'action_0', etc.) and appropriate 'properties' matching their template.
Position nodes clearly: Cues on the left, conditions to their right, and action chains horizontally to the right.`;

    const phase1Schema = {
      type: Type.OBJECT,
      required: ["name", "version", "author", "description", "nodes"],
      properties: {
        name: { type: Type.STRING, description: "Alphanumeric mod name with underscores, e.g. Bounty_Killer_Mod" },
        version: { type: Type.STRING },
        author: { type: Type.STRING },
        description: { type: Type.STRING },
        nodes: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            required: ["id", "type", "label", "xmlTag", "x", "y", "properties"],
            properties: {
              id: { type: Type.STRING },
              type: { type: Type.STRING, description: "cue, event, condition, or action" },
              label: { type: Type.STRING },
              xmlTag: { type: Type.STRING },
              x: { type: Type.NUMBER },
              y: { type: Type.NUMBER },
              properties: {
                type: Type.OBJECT,
                description: "Properties for the node. E.g. for cue: {name, instantiate, namespace, state}. For event/condition/action: relevant keys according to their templates."
              },
              comment: { type: Type.STRING }
            }
          }
        }
      }
    };

    let phase1Prompt = `Prompt: "${prompt}"`;
    if (baseWorkspace) {
      const promptNodes = (baseWorkspace.nodes || []).map((node: any) => ({
        id: node.id,
        type: node.type,
        label: node.label,
        xmlTag: node.xmlTag,
        x: node.x,
        y: node.y,
        properties: node.properties
      }));
      phase1Prompt = `You are modifying an existing ModWorkspace layout.
[Current Workspace Structure]:
- Name: "${baseWorkspace.name}"
- Version: "${baseWorkspace.version || "1.0.0"}"
- Author: "${baseWorkspace.author || ""}"
- Description: "${baseWorkspace.description || ""}"
- Current Nodes: ${JSON.stringify(promptNodes)}
- Non-MD domains to preserve unless the user explicitly asks to change them: ${JSON.stringify(summarizeWorkspaceDomains(baseWorkspace))}

Modify these nodes or add new ones to satisfy this prompt:
"${prompt}"

Maintain as many existing nodes as possible unless they require replacement.`;
    }

    const phase1RawResult = await callMultiProviderAI(req, phase1System, phase1Prompt, "json", phase1Schema);
    const phase1Result = JSON.parse(phase1RawResult.trim());
    
    // Auto-populate port signatures and property schemas from source dictionary to ensure 100% compliance
    const populatedNodes = populateNodeMetadata(phase1Result.nodes);

    // --- PHASE 2: RELATIONAL WIRE LOGIC LINKEAGES ---
    console.log(`[AI-STUDIO] [Phase 2/4] Constructing Relational Wire Linkages...`);
    const phase2System = `You are Phase 2 of a visual workspace translator. Given the populated list of visual nodes (cues, events, conditions, actions), define how they connect together.
Return ONLY the links connection list matching the specified JSON schema.

CRITICAL LINKING RULES:
1. Connect conditions/events to their cue: sourceNodeId is the cue, sourcePortId="out_cond", targetNodeId is the event/condition, targetPortId="in_cond".
2. Connect the first action of a cue: sourceNodeId is the cue, sourcePortId="out_act", targetNodeId is the first action, targetPortId="in_act".
3. Chain subsequent actions together: sourceNodeId is the previous action, sourcePortId="out_next", targetNodeId is the next action, targetPortId="in_act".
4. Connect child cues to parent cues for nested sub-cues: sourceNodeId is parent, sourcePortId="out_sub", targetNodeId is the child cue, targetPortId="in_flow".`;

    const phase2Schema = {
      type: Type.OBJECT,
      required: ["links"],
      properties: {
        links: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            required: ["id", "sourceNodeId", "sourcePortId", "targetNodeId", "targetPortId"],
            properties: {
              id: { type: Type.STRING },
              sourceNodeId: { type: Type.STRING, description: "ID of the source node" },
              sourcePortId: { type: Type.STRING, description: "out_cond, out_act, out_next, or out_sub" },
              targetNodeId: { type: Type.STRING, description: "ID of the target node" },
              targetPortId: { type: Type.STRING, description: "in_cond, in_act, or in_flow" }
            }
          }
        }
      }
    };

    const phase2Prompt = `Construct logic link arrays for this workspace layout.
[Populated Nodes Layout]:
${JSON.stringify(populatedNodes.map(n => ({ id: n.id, label: n.label, type: n.type, xmlTag: n.xmlTag, inputs: n.inputs, outputs: n.outputs })))}

[User Prompt Requirement Context]:
"${prompt}"

Please connect the nodes logically. For example, connect a Cue node's outputs ('out_cond' / 'out_act') to its associated Event or Action node inputs ('in_cond' / 'in_act').`;

    const phase2RawResult = await callMultiProviderAI(req, phase2System, phase2Prompt, "json", phase2Schema);
    const phase2Result = JSON.parse(phase2RawResult.trim());

    // --- PHASE 3: HUD USER CONTROL INTERFACES ---
    console.log(`[AI-STUDIO] [Phase 3/4] Designing Graphic Interface Control overlays...`);
    const phase3System = `You are Phase 3 of a visual workspace translator. Design or edit active web graphic HUD dashboard widgets and custom UI themes that fit the mod behavior.
Ensure that smaller UI elements (progressbar, buttons, checkboxes, input text) are styled and positioned visually inside container "window" elements (w, h heights).
Return ONLY the uiWidgets and uiTheme block fit.`;

    const phase3Schema = {
      type: Type.OBJECT,
      required: ["uiWidgets", "uiTheme"],
      properties: {
        uiWidgets: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            required: ["id", "type", "x", "y", "w", "h", "label", "properties"],
            properties: {
              id: { type: Type.STRING },
              type: { type: Type.STRING, description: "window, table, button, progressbar, check, text, dropdown, header, input, chat" },
              x: { type: Type.NUMBER },
              y: { type: Type.NUMBER },
              w: { type: Type.NUMBER },
              h: { type: Type.NUMBER },
              label: { type: Type.STRING },
              properties: { type: Type.OBJECT }
            }
          }
        },
        uiTheme: {
          type: Type.OBJECT,
          required: ["backgroundColor", "borderColor", "accentColor", "opacity", "showIcons"],
          properties: {
            backgroundColor: { type: Type.STRING },
            borderColor: { type: Type.STRING },
            accentColor: { type: Type.STRING },
            opacity: { type: Type.NUMBER },
            showIcons: { type: Type.BOOLEAN }
          }
        }
      }
    };

    const currentUIWidgets = baseWorkspace.uiWidgets || [];
    const currentUITheme = baseWorkspace.uiTheme || {
      backgroundColor: "#0d1117",
      borderColor: "#df9825",
      accentColor: "#f39c12",
      opacity: 0.85,
      showIcons: true
    };

    const phase3Prompt = `Add or adjust visual HUD display control widgets.
[User Request]:
"${prompt}"

[Nodes Created]:
${JSON.stringify(populatedNodes.map(n => ({ id: n.id, label: n.label, xmlTag: n.xmlTag })))}

[Current HUD widgets]:
${JSON.stringify(currentUIWidgets)}

Create, update, or reposition HUD window containers and nested controller elements to fit the mod. Return the compiled array.`;

    const phase3RawResult = await callMultiProviderAI(req, phase3System, phase3Prompt, "json", phase3Schema);
    const phase3Result = JSON.parse(phase3RawResult.trim());

    // --- PACK COMBINED EXPERIMENT STAGE ---
    let combinedWorkspace: ModWorkspace = {
      ...baseWorkspace,
      id: `workspace_${Date.now()}`,
      name: phase1Result.name || (baseWorkspace.name || "My_Custom_Mod"),
      version: phase1Result.version || (baseWorkspace.version || "1.0.0"),
      author: phase1Result.author || (baseWorkspace.author || "Player"),
      description: phase1Result.description || (baseWorkspace.description || ""),
      nodes: populatedNodes,
      links: phase2Result.links || [],
      uiWidgets: phase3Result.uiWidgets || [],
      uiTheme: phase3Result.uiTheme || currentUITheme
    };

    // --- PHASE 4: EXPERT SCHEMA SELF-REPAIR SANITY VET ---
    console.log(`[AI-STUDIO] [Phase 4/4] Executing Egosoft Schema Verification & Healing...`);
    const currentCode = generateMDXML(combinedWorkspace);
    const validationDiagnostics = validateModWorkspace(combinedWorkspace, currentCode);

    if (validationDiagnostics.length > 0) {
      console.log(`[AI-STUDIO] Validation reported ${validationDiagnostics.length} warnings. Running auto-remedy fix...`);
      
      const phase4System = `You are Phase 4 (Self-Healing Compiler) for the X4 Foundations visual editor.
The generated workspace layout currently fails Egosoft's visual schema checks with specific warnings/errors.
Study the diagnostics report, apply corrections to the nodes, properties, and links, and return the absolute complete ModWorkspace JSON.

CRITICAL COMPLIANCE RULES:
1. Visual Event, Condition, and Action nodes must be linked correctly to their respective parent Cue node.
2. Conditions/events connect via Cue's out_cond to Condition's in_cond.
3. Actions connect sequentially starting from Cue's out_act to first Action's in_act, then Action's out_next to next Action's in_act.
4. Child cues connect via parent Cue's out_sub to child Cue's in_flow.`;

      const phase4Schema = {
        type: Type.OBJECT,
        required: ["name", "version", "author", "description", "nodes", "links", "uiWidgets", "uiTheme"],
        properties: {
          name: { type: Type.STRING },
          version: { type: Type.STRING },
          author: { type: Type.STRING },
          description: { type: Type.STRING },
          nodes: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              required: ["id", "type", "label", "xmlTag", "x", "y", "properties"],
              properties: {
                id: { type: Type.STRING },
                type: { type: Type.STRING },
                label: { type: Type.STRING },
                xmlTag: { type: Type.STRING },
                x: { type: Type.NUMBER },
                y: { type: Type.NUMBER },
                properties: {
                  type: Type.OBJECT,
                  description: "Properties for the node. E.g. for cue: {name, instantiate, namespace, state}. For event/condition/action: relevant keys according to their templates."
                },
                comment: { type: Type.STRING }
              }
            }
          },
          links: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              required: ["id", "sourceNodeId", "sourcePortId", "targetNodeId", "targetPortId"],
              properties: {
                id: { type: Type.STRING },
                sourceNodeId: { type: Type.STRING },
                sourcePortId: { type: Type.STRING },
                targetNodeId: { type: Type.STRING },
                targetPortId: { type: Type.STRING }
              }
            }
          },
          uiWidgets: { type: Type.ARRAY, items: { type: Type.OBJECT } },
          uiTheme: { type: Type.OBJECT }
        }
      };

      const phase4Prompt = `Correct the layout parameters of this ModWorkspace structure.
[Damaged Workspace Layout]:
${JSON.stringify({
  name: combinedWorkspace.name,
  description: combinedWorkspace.description,
  nodes: combinedWorkspace.nodes.map(n => ({ id: n.id, xmlTag: n.xmlTag, properties: n.properties })),
  links: combinedWorkspace.links
})}

[Egosoft Validation Diagnostics Code Reports]:
${JSON.stringify(validationDiagnostics, null, 2)}

Please edit the links or properties to resolve all errors in the diagnostic suite. Output the corrected variables.`;

      try {
        const phase4Raw = await callMultiProviderAI(req, phase4System, phase4Prompt, "json", phase4Schema);
        const phase4Result = JSON.parse(phase4Raw.trim());
        
        // Re-populate system metadata to guarantee property schemas remain undamaged
        const fixedNodes = populateNodeMetadata(phase4Result.nodes);
        
        combinedWorkspace = {
          ...combinedWorkspace,
          name: phase4Result.name || combinedWorkspace.name,
          nodes: fixedNodes,
          links: phase4Result.links || combinedWorkspace.links,
          uiWidgets: phase4Result.uiWidgets || combinedWorkspace.uiWidgets,
          uiTheme: phase4Result.uiTheme || combinedWorkspace.uiTheme
        };
        console.log(`[AI-STUDIO] Phased Auto-Remedy cycle completed successfully.`);
      } catch (repairErr) {
        console.warn(`[AI-STUDIO] Self-heal attempt failed (ignoring, falling back to base layout):`, repairErr);
      }
    } else {
      console.log(`[AI-STUDIO] Verification complete: pristine schema validated on first run.`);
    }

    // Apply globally to the shared space
    activeWorkspace = combinedWorkspace;
    workspaceVersion++;

    console.log(`[AI-STUDIO] Phased interpretation complete. Delivered blueprint named: ${combinedWorkspace.name}`);

    const finalCode = generateMDXML(combinedWorkspace);
    const finalDiagnostics = validateModWorkspace(combinedWorkspace, finalCode);

    return res.json({
      success: true,
      message: "AI Agent successfully designed and applied a new mod schema to the workspace in 4 distinct high-fidelity phases!",
      version: workspaceVersion,
      workspace: combinedWorkspace,
      diagnostics: finalDiagnostics,
      selfHealFailed: validationDiagnostics.length > 0 && finalDiagnostics.length > 0
    });

  } catch (error: any) {
    console.error("AI Agent layout generation error: ", error);
    return res.status(500).json({
      error: error.message || "Failed to trigger automated workspace planner in phased execution mode."
    });
  }
});


// -----------------------------------------------------
// 3. SECURE GITHUB API SYSTEM PROXY
// -----------------------------------------------------

app.post("/api/github/load", async (req, res) => {
  const { pat, owner, repo, path: filePath, branch } = req.body;
  
  if (!owner || !repo || !filePath) {
    return res.status(400).json({ error: "Missing repo parameters (owner, repo, or path)." });
  }

  // Token is optional if repo is public, but helpful to configure
  const headers: Record<string, string> = {
    "Accept": "application/vnd.github.v3+json",
    "User-Agent": "x4-md-studio-proxy"
  };

  if (pat) {
    headers["Authorization"] = `token ${pat}`;
  }

  try {
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}?ref=${branch || "main"}`;
    const response = await fetch(url, { headers });
    
    if (!response.ok) {
      const errorText = await response.text();
      return res.status(response.status).json({
        error: `GitHub returned error: ${response.statusText}`,
        details: errorText
      });
    }
    
    const data: any = await response.json();
    if (data.type !== "file") {
      return res.status(400).json({ error: "Selected path is not a single file." });
    }

    const decoded = Buffer.from(data.content, "base64").toString("utf-8");
    return res.json({
      success: true,
      sha: data.sha,
      content: decoded,
      fileName: data.name
    });
  } catch (error: any) {
    console.error("GitHub file load error: ", error);
    return res.status(500).json({ error: error.message || "Failed to load file from GitHub." });
  }
});

app.post("/api/github/push", async (req, res) => {
  const { pat, owner, repo, branch, commitMessage, files } = req.body;

  if (!pat) {
    return res.status(400).json({ error: "GitHub Personal Access Token (PAT) is required." });
  }
  if (!owner || !repo) {
    return res.status(400).json({ error: "Owner and repository name are required." });
  }
  if (!files || !Array.isArray(files) || files.length === 0) {
    return res.status(400).json({ error: "No files provided to push." });
  }

  const selectedBranch = branch || "main";
  const msg = commitMessage || "Update mod files from X4:MD Studio";
  const results: any[] = [];

  try {
    // For each file, we'll sequentially commit it
    for (const file of files) {
      const { path: filePath, content } = file;
      if (!filePath || content === undefined) continue;

      const headers: Record<string, string> = {
        "Accept": "application/vnd.github.v3+json",
        "Authorization": `token ${pat}`,
        "User-Agent": "x4-md-studio-proxy"
      };

      // 1. Get the pre-existing SHA if it exists
      let currentSha: string | undefined;
      const getUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}?ref=${selectedBranch}`;
      
      try {
        const getRes = await fetch(getUrl, { headers });
        if (getRes.status === 200) {
          const getData: any = await getRes.json();
          currentSha = getData.sha;
        }
      } catch (getErr) {
        // Log error but ignore (might be new file)
        console.log(`Pre-fetch SHA failed for ${filePath}, assuming new file.`);
      }

      // 2. Put file contents back
      const putUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`;
      const base64Content = Buffer.from(content).toString("base64");
      
      const bodyPayload: any = {
        message: msg,
        content: base64Content,
        branch: selectedBranch
      };
      
      if (currentSha) {
        bodyPayload.sha = currentSha;
      }

      const putRes = await fetch(putUrl, {
        method: "PUT",
        headers: {
          ...headers,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(bodyPayload)
      });

      if (!putRes.ok) {
        const errDetails = await putRes.text();
        throw new Error(`Failed to push file: ${filePath}. Status: ${putRes.status}, Response: ${errDetails}`);
      }

      const putData: any = await putRes.json();
      results.push({
        path: filePath,
        sha: putData.content.sha,
        success: true
      });
    }

    return res.json({
      success: true,
      message: `Successfully pushed ${results.length} files to ${owner}/${repo} on branch ${selectedBranch}.`,
      results
    });

  } catch (error: any) {
    console.error("GitHub push error: ", error);
    return res.status(500).json({ error: error.message || "Failed to commit files to GitHub." });
  }
});


/**
 * POST /api/github/create
 * Creates a new GitHub repository under the authenticated user (from the PAT),
 * so a mod-in-progress can be published as a fresh repo in one click.
 */
app.post("/api/github/create", async (req, res) => {
  const { pat, name, description, private: isPrivate } = req.body;

  if (!pat) {
    return res.status(400).json({ error: "GitHub Personal Access Token (PAT) is required." });
  }
  if (!name) {
    return res.status(400).json({ error: "Repository name is required." });
  }

  try {
    const response = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: {
        "Accept": "application/vnd.github.v3+json",
        "Authorization": `token ${pat}`,
        "User-Agent": "x4-md-studio-proxy",
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        name,
        description: description || "X4 Foundations mod created with X4:MD Studio",
        private: !!isPrivate,
        auto_init: false
      })
    });

    const data: any = await response.json();
    if (!response.ok) {
      return res.status(response.status).json({
        error: data?.message || `GitHub returned error code ${response.status}`,
        details: data?.errors
      });
    }

    return res.json({
      success: true,
      owner: data.owner?.login,
      repo: data.name,
      full_name: data.full_name,
      html_url: data.html_url,
      default_branch: data.default_branch || "main"
    });
  } catch (error: any) {
    console.error("GitHub create-repo error: ", error);
    return res.status(500).json({ error: error.message || "Failed to create GitHub repository." });
  }
});


/**
 * POST /api/github/device/start
 * Begins the GitHub OAuth Device Flow: requests a device + user code so the user can
 * authorize in their browser (no PAT copy-paste, no client secret needed).
 */
app.post("/api/github/device/start", async (req, res) => {
  const clientId = String(req.body?.client_id || process.env.GITHUB_CLIENT_ID || "").trim();
  const scope = String(req.body?.scope || "repo").trim();
  if (!clientId) {
    return res.status(400).json({ error: "Missing GitHub OAuth Client ID. Register an OAuth App (with Device Flow enabled) and provide its Client ID." });
  }
  try {
    const response = await fetch("https://github.com/login/device/code", {
      method: "POST",
      headers: { "Accept": "application/json", "Content-Type": "application/json", "User-Agent": "x4-md-studio" },
      body: JSON.stringify({ client_id: clientId, scope })
    });
    const data: any = await response.json();
    if (!response.ok || data.error) {
      return res.status(400).json({ error: data.error_description || data.error || "Failed to start GitHub device authorization." });
    }
    // data: device_code, user_code, verification_uri, expires_in, interval
    return res.json(data);
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Device authorization request failed." });
  }
});

/**
 * POST /api/github/device/poll
 * Polls GitHub for the device-flow access token. Returns { pending: true } until the
 * user approves, then { access_token, login } once authorized.
 */
app.post("/api/github/device/poll", async (req, res) => {
  const clientId = String(req.body?.client_id || process.env.GITHUB_CLIENT_ID || "").trim();
  const deviceCode = String(req.body?.device_code || "").trim();
  if (!clientId || !deviceCode) {
    return res.status(400).json({ error: "Missing client_id or device_code." });
  }
  try {
    const response = await fetch("https://github.com/login/oauth/access_token", {
      method: "POST",
      headers: { "Accept": "application/json", "Content-Type": "application/json", "User-Agent": "x4-md-studio" },
      body: JSON.stringify({
        client_id: clientId,
        device_code: deviceCode,
        grant_type: "urn:ietf:params:oauth:grant-type:device_code"
      })
    });
    const data: any = await response.json();

    if (data.access_token) {
      // Fetch the authenticated user's login so the client can auto-fill the repo owner.
      let login: string | undefined;
      try {
        const userRes = await fetch("https://api.github.com/user", {
          headers: {
            "Accept": "application/vnd.github.v3+json",
            "Authorization": `token ${data.access_token}`,
            "User-Agent": "x4-md-studio"
          }
        });
        const userData: any = await userRes.json();
        login = userData?.login;
      } catch {
        // Non-fatal; owner can be entered manually.
      }
      return res.json({ access_token: data.access_token, token_type: data.token_type, scope: data.scope, login });
    }

    // Still waiting / throttled / expired — surface the GitHub error code to the poller.
    return res.json({ pending: true, error: data.error, interval: data.interval });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Device token poll failed." });
  }
});


/**
 * POST /api/github/commits
 * Returns the real commit history for the connected repo/branch so the Graph Log
 * reflects the actual mod repository instead of seeded placeholder data.
 */
app.post("/api/github/commits", async (req, res) => {
  const { pat, owner, repo, branch } = req.body;
  if (!pat || !owner || !repo) {
    return res.status(400).json({ error: "Missing pat, owner, or repo." });
  }
  try {
    const url = `https://api.github.com/repos/${owner}/${repo}/commits?sha=${encodeURIComponent(branch || "main")}&per_page=50`;
    const response = await fetch(url, {
      headers: {
        "Accept": "application/vnd.github.v3+json",
        "Authorization": `token ${pat}`,
        "User-Agent": "x4-md-studio-proxy"
      }
    });
    const data: any = await response.json();
    if (!response.ok) {
      return res.status(response.status).json({ error: data?.message || `GitHub returned ${response.status}` });
    }
    const commits = (Array.isArray(data) ? data : []).map((c: any) => ({
      sha: (c.sha || "").substring(0, 7),
      message: (c.commit?.message || "").split("\n")[0],
      body: c.commit?.message || "",
      author: c.commit?.author?.name || c.author?.login || "unknown",
      email: c.commit?.author?.email || "",
      date: c.commit?.author?.date || "",
      html_url: c.html_url
    }));
    return res.json({ commits });
  } catch (error: any) {
    return res.status(500).json({ error: error.message || "Failed to fetch repository commits." });
  }
});


// Configure Vite middleware or static serving
async function setupDevOrProd() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.get("/", async (req, res, next) => {
      try {
        const template = fs.readFileSync(path.join(process.cwd(), "index.html"), "utf8");
        const html = await vite.transformIndexHtml(req.originalUrl, injectStudioToken(template));
        res.status(200).set({ "Content-Type": "text/html" }).end(html);
      } catch (error) {
        vite.ssrFixStacktrace(error as Error);
        next(error);
      }
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      const html = fs.readFileSync(path.join(distPath, "index.html"), "utf8");
      res.status(200).set({ "Content-Type": "text/html" }).end(injectStudioToken(html));
    });
  }
}

setupDevOrProd().then(() => {
  app.listen(PORT, "127.0.0.1", () => {
    console.log(`X4 Mod Studio Dev Server running on http://127.0.0.1:${PORT}`);
  });
}).catch(err => {
  console.error("Server failure: ", err);
});
