/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import {
  Clipboard,
  Check,
  Download,
  Terminal,
  FileCode,
  FileJson,
  Sparkles,
  Folder,
  Save,
  X,
  PackageCheck,
  Split
} from 'lucide-react';
import { ModWorkspace, generateMDXML, generateUIXML, MDNode, PackageDiagnostic } from '../types';
import { parseXMLToWorkspace } from '../lib/xmlParser';
import CodeMirrorField from './CodeMirrorField';

// B48: the real editor engine (CodeMirror 6) replaces the hand-rolled textarea/pre editor and
// custom diff renderer. Flag kept so the old renderer stays reachable as a one-release fallback.
const CODEMIRROR_EDITOR = true;
import {
  toSafeModId,
  generateContentXML,
  compileScriptToXML,
  compileWaresXML,
  compileJobsXML,
  compileTFileXML,
  compileDiffDocument,
  toTFileName
} from '../lib/modCompiler';

export interface EditorFile {
  name: string;
  path: string;
  content: string;
  handle?: unknown;
  isMock?: boolean;
}

export interface DiffLine {
  type: 'added' | 'removed' | 'unchanged' | 'empty';
  value: string;
  originalLineNumber?: number;
  modifiedLineNumber?: number;
}

interface CodePreviewProps {
  workspace: ModWorkspace;
  setWorkspace?: React.Dispatch<React.SetStateAction<ModWorkspace>>;
  activeMdScript?: string | null;
  setActiveMdScript?: (s: string | null) => void;
  saveCheckpoint?: (customTarget?: ModWorkspace) => void;
  modWorkspacePath: string;
  activeEditorFile: EditorFile | null;
  setActiveEditorFile: React.Dispatch<React.SetStateAction<EditorFile | null>>;
  selectedNode: MDNode | null;
  compileStatus: 'idle' | 'compiling' | 'success' | 'error';
  compileMessage: string;
  handleCompileModProject: () => Promise<void>;
  diagnostics: PackageDiagnostic[];
  diagnosticSource: 'checking' | 'package' | 'local';
  snapshotDiffWorkspace: ModWorkspace | null;
  onClearSnapshotDiff?: () => void;
  selectedCueIds: string[];
  autoSaveEnabled?: boolean;
  setAutoSaveEnabled?: (val: boolean) => void;
  codeCollapsed?: boolean;
  setCodeCollapsed?: (val: boolean) => void;
  /** When provided, the tab+action chrome bar renders into THIS element (a persistent
   *  top bar outside the editor) instead of inline — so the editor stays code-only. */
  topBarTarget?: HTMLElement | null;
}

function messageFromUnknown(error: unknown, fallback: string): string {
  return error instanceof Error ? error.message : fallback;
}

function getSnapshotContentForPath(snapWS: ModWorkspace, relativePath: string): string {
  const normPath = relativePath.replace(/\\/g, '/').replace(/^\.\//, '').replace(/^\//, '');
  const modId = toSafeModId(snapWS.name);

  // 1. content.xml
  if (normPath === 'content.xml') {
    return generateContentXML(modId, snapWS);
  }

  // 2. README.md
  if (normPath.toLowerCase() === 'readme.md') {
    return `# ${snapWS.name || modId}\n\nGenerated by X4 Forge.\n`;
  }

  // 3. md/<modId>.xml
  if (normPath.startsWith('md/') && normPath.endsWith('.xml')) {
    return generateMDXML(snapWS);
  }

  // 4. UI Layouts
  if (normPath.startsWith('md_ui_layouts/') && normPath.endsWith('.xml')) {
    return generateUIXML(snapWS);
  }

  // 5. AIScripts
  if (normPath.startsWith('aiscripts/') && normPath.endsWith('.xml')) {
    const fileName = normPath.substring('aiscripts/'.length);
    const scriptName = fileName.replace('.xml', '');
    const script = snapWS.aiScripts?.find(s => s.name === scriptName || s.name + '.xml' === fileName);
    if (script) {
      return compileScriptToXML(script);
    }
  }

  // 6. Wares and Jobs in libraries/
  if (normPath === 'libraries/wares.xml') {
    return compileWaresXML(snapWS.wares || []);
  }
  if (normPath === 'libraries/jobs.xml') {
    return compileJobsXML(snapWS.jobs || []);
  }

  // 7. Translations in t/
  if (normPath.startsWith('t/') && normPath.endsWith('.xml')) {
    const fileName = normPath.substring('t/'.length);
    const tFile = snapWS.tFiles?.find(f => f.fileName === fileName || toTFileName(f) === fileName);
    if (tFile) {
      return compileTFileXML(tFile);
    }
  }

  // 8. XML diff patches (by targetFile path)
  if (snapWS.xmlPatches?.length) {
    const patches = snapWS.xmlPatches.filter(p => {
      const pTarget = (p.targetFile || '').replace(/\\/g, '/').replace(/^\.\//, '').replace(/^\//, '');
      return pTarget === normPath;
    });
    if (patches.length > 0) {
      return compileDiffDocument(patches, normPath);
    }
  }

  return '';
}

export default function CodePreview({
  workspace,
  setWorkspace,
  activeMdScript = null,
  setActiveMdScript,
  saveCheckpoint,
  modWorkspacePath,
  activeEditorFile,
  setActiveEditorFile,
  selectedNode,
  compileStatus,
  compileMessage: _compileMessage,
  handleCompileModProject,
  diagnostics,
  diagnosticSource: _diagnosticSource,
  snapshotDiffWorkspace,
  onClearSnapshotDiff,
  selectedCueIds,
  autoSaveEnabled: propAutoSaveEnabled,
  setAutoSaveEnabled: _propSetAutoSaveEnabled,
  codeCollapsed: _codeCollapsed,
  setCodeCollapsed: _setCodeCollapsed,
  topBarTarget
}: CodePreviewProps) {
  const [codeActiveTab, setCodeActiveTab] = useState<'md' | 'ui' | 'node' | 'file'>('md');
  // activeMdScript / setActiveMdScript now come from props (shared with the canvas).
  const [, setToolActiveTab] = useState<'analyzer' | 'playtest'>('analyzer');
  const [copied, setCopied] = useState<boolean>(false);

  // Playtest Live Debugger states
  const [, setSyncStatus] = useState<'idle' | 'syncing' | 'success' | 'error'>('idle');
  const [, setSyncErrorMsg] = useState<string>('');

  const [localAutoSaveEnabled] = useState<boolean>(false);
  const autoSaveEnabled = propAutoSaveEnabled !== undefined ? propAutoSaveEnabled : localAutoSaveEnabled;

  // File Editor states
  const [editorContent, setEditorContent] = useState<string>('');
  const [editorSaveStatus, setEditorSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
  const [editorError, setEditorError] = useState<string>('');
  const [generatedDraft, setGeneratedDraft] = useState<string>('');
  const [generatedDraftKey, setGeneratedDraftKey] = useState<string>('');
  const [generatedDraftDirty, setGeneratedDraftDirty] = useState<boolean>(false);
  const [generatedApplyStatus, setGeneratedApplyStatus] = useState<'idle' | 'applying' | 'applied' | 'error'>('idle');
  const [generatedApplyMessage, setGeneratedApplyMessage] = useState<string>('');
  const [generatedEditorScroll, setGeneratedEditorScroll] = useState({ top: 0, left: 0 });
  const [splitEditorScroll, setSplitEditorScroll] = useState({ top: 0, left: 0 });

  // ================================================================ 
  // CUSTOM ANTI-GRAVITY IDE & DIFF PREVIEWER CONTEXTUAL VARIABLESS 
  // ================================================================ 
  interface Tab {
    id: string; // 'md', 'ui', 'node', or filesystem file path
    name: string;
    type: 'md' | 'ui' | 'node' | 'file';
    path?: string;
  }

  const [openTabs, setOpenTabs] = useState<Tab[]>([
    { id: 'md', name: 'MD.xml', type: 'md' },
    { id: 'ui', name: 'UI_LAYOUT.xml', type: 'ui' }
  ]);
  const [openFilesMap, setOpenFilesMap] = useState<Record<string, { name: string, path: string, content: string, originalContent: string }>>({});

  const [diffEnabled, setDiffEnabled] = useState<boolean>(false);
  const [diffMode, setDiffMode] = useState<'split' | 'unified'>('split');
  const [diffBaseType, setDiffBaseType] = useState<'compile' | 'original'>('compile');
  
  const effectiveDiffEnabled = diffEnabled || !!snapshotDiffWorkspace;

  // Auto-hide the code minimap in a narrow panel (G8b): the VS Code–style overview steals
  // ~40px and is low-value below this width. A CALLBACK ref reliably attaches a ResizeObserver
  // the moment the root mounts (a plain ref + [] effect missed it when the root rendered after
  // an early return), so the width tracks live as the user resizes the panel.
  const [editorWidth, setEditorWidth] = React.useState<number>(9999);
  const minimapObserverRef = React.useRef<ResizeObserver | null>(null);
  const setEditorRoot = React.useCallback((el: HTMLDivElement | null) => {
    minimapObserverRef.current?.disconnect();
    if (el && typeof ResizeObserver !== 'undefined') {
      setEditorWidth(el.getBoundingClientRect().width);
      minimapObserverRef.current = new ResizeObserver(entries => {
        for (const e of entries) setEditorWidth(e.contentRect.width);
      });
      minimapObserverRef.current.observe(el);
    }
  }, []);
  const showMinimap = editorWidth >= 560;

  // Baseline copies for live modifications comparisons
  const [initialMDCode, setInitialMDCode] = useState<string>('');
  const [initialUICode, setInitialUICode] = useState<string>('');
  const [originalMD, setOriginalMD] = useState<string>('');
  const [originalUI, setOriginalUI] = useState<string>('');

  const [initialWorkspace, setInitialWorkspace] = useState<ModWorkspace | null>(null);
  const [lastCompiledWorkspace, setLastCompiledWorkspace] = useState<ModWorkspace | null>(null);

  useEffect(() => {
    if (!initialWorkspace && workspace) {
      setInitialWorkspace(JSON.parse(JSON.stringify(workspace)));
    }
    // reason: one-shot baseline capture; re-running on initialWorkspace would clobber the baseline.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workspace]);

  useEffect(() => {
    if (compileStatus === 'success') {
      setLastCompiledWorkspace(JSON.parse(JSON.stringify(workspace)));
    }
    // reason: snapshot must capture workspace at the moment of compile only; adding workspace would re-snapshot on every edit and break the "last compiled" baseline.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [compileStatus]);

  // Multi-script "view all": when the workspace holds cues from >1 script (tagged mdFileStem
  // on import), render EACH as its own <mdscript> with a file header — so the panel shows the
  // real per-file output, not one wrong mashed-together script. Single-script mods unchanged.
  const buildAllScriptsMd = (ws: ModWorkspace): string => {
    const cues = (ws.nodes || []).filter(n => n.type === 'cue');
    const subIds = new Set((ws.links || []).filter(l => l.sourcePortId === 'out_sub').map(l => l.targetNodeId));
    const stems = Array.from(new Set(cues.map(c => (c.properties as any)?.mdFileStem).filter((s: any): s is string => typeof s === 'string')));
    if (stems.length <= 1) return generateMDXML(ws);
    return stems.map(stem => {
      const top = cues.filter(c => (c.properties as any)?.mdFileStem === stem && !subIds.has(c.id)).map(c => c.id);
      const name = (cues.find(c => (c.properties as any)?.mdFileStem === stem)?.properties as any)?.mdScript || stem;
      return `<!-- ════════ md/${stem}.xml ════════ -->\n` + generateMDXML(ws, top, name);
    }).join('\n\n');
  };
  const mdCode = selectedCueIds && selectedCueIds.length > 0
    ? generateMDXML(workspace, selectedCueIds)
    : (activeMdScript
        ? generateMDXML(
            workspace,
            (workspace.nodes || []).filter(n => n.type === 'cue' && (n.properties as any)?.mdFileStem === activeMdScript && !new Set((workspace.links || []).filter(l => l.sourcePortId === 'out_sub').map(l => l.targetNodeId)).has(n.id)).map(n => n.id),
            activeMdScript
          )
        : buildAllScriptsMd(workspace));
  const uiCode = generateUIXML(workspace);

  const collectDownstreamNodeIds = (startIds: string[], sourceWorkspace: ModWorkspace = workspace): Set<string> => {
    const ids = new Set<string>(startIds);
    const queue = [...startIds];
    while (queue.length > 0) {
      const sourceId = queue.shift()!;
      sourceWorkspace.links
        .filter(link => link.sourceNodeId === sourceId)
        .forEach(link => {
          if (!ids.has(link.targetNodeId)) {
            ids.add(link.targetNodeId);
            queue.push(link.targetNodeId);
          }
        });
    }
    return ids;
  };

  const generateSelectedNodeHierarchyXML = (node: MDNode | null, sourceWorkspace: ModWorkspace = workspace): string => {
    if (!node) return '';
    if (node.type === 'cue') {
      return generateMDXML(sourceWorkspace, [node.id]);
    }

    const downstreamIds = collectDownstreamNodeIds([node.id], sourceWorkspace);
    const selectedNodes = sourceWorkspace.nodes.filter(n => downstreamIds.has(n.id));
    const selectedNodeIds = new Set(selectedNodes.map(n => n.id));
    const syntheticCue: MDNode = {
      id: '__preview_selected_node_cue__',
      type: 'cue',
      label: `Preview: ${node.label}`,
      xmlTag: 'cue',
      x: 0,
      y: 0,
      properties: {
        name: `Preview_${node.properties?.name || node.label || node.xmlTag}`,
        instantiate: 'false',
        namespace: 'this'
      },
      propertiesSchema: [],
      inputs: [],
      outputs: []
    };

    const hierarchyLinks = sourceWorkspace.links.filter(link =>
      selectedNodeIds.has(link.sourceNodeId) && selectedNodeIds.has(link.targetNodeId)
    );
    const syntheticLinks = [
      {
        id: '__preview_selected_node_link__',
        sourceNodeId: syntheticCue.id,
        sourcePortId: node.type === 'action' ? 'out_act' : 'out_cond',
        targetNodeId: node.id,
        targetPortId: node.type === 'action' ? 'in_act' : 'in_cond'
      },
      ...sourceWorkspace.links
        .filter(link => link.sourceNodeId === node.id && link.sourcePortId === 'out_flow')
        .map(link => ({
          id: `__preview_flow_${link.id}`,
          sourceNodeId: syntheticCue.id,
          sourcePortId: 'out_act',
          targetNodeId: link.targetNodeId,
          targetPortId: 'in_act'
        })),
      ...hierarchyLinks
    ];

    return generateMDXML({
      ...sourceWorkspace,
      nodes: [syntheticCue, ...selectedNodes],
      links: syntheticLinks
    }, [syntheticCue.id]);
  };

  let currentCode = '';
  if (codeActiveTab === 'md') {
    currentCode = selectedNode ? generateSelectedNodeHierarchyXML(selectedNode) : mdCode;
  } else if (codeActiveTab === 'ui') {
    currentCode = uiCode;
  } else if (codeActiveTab === 'node') {
    currentCode = generateSelectedNodeHierarchyXML(selectedNode);
  } else if (codeActiveTab === 'file') {
    currentCode = editorContent;
  }

  const workspaceSerialized = JSON.stringify({
    name: workspace.name,
    description: workspace.description,
    author: workspace.author,
    version: workspace.version,
    compileSettings: workspace.compileSettings,
    nodes: workspace.nodes.map(n => ({ id: n.id, type: n.type, label: n.label, xmlTag: n.xmlTag, properties: n.properties, includeInBuild: n.includeInBuild })),
    links: workspace.links,
    uiWidgets: workspace.uiWidgets.map(w => ({ id: w.id, type: w.type, label: w.label, properties: w.properties, w: w.w, h: w.h, includeInBuild: w.includeInBuild })),
    uiTheme: workspace.uiTheme,
    aiScripts: workspace.aiScripts,
    wares: workspace.wares,
    jobs: workspace.jobs,
    tFiles: workspace.tFiles,
    xmlPatches: workspace.xmlPatches
  });

  const generatedDraftSourceKey = JSON.stringify({
    tab: codeActiveTab,
    selectedNodeId: selectedNode?.id || null,
    selectedCueIds,
    activeFilePath: activeEditorFile?.path || null,
    workspaceSerialized
  });

  useEffect(() => {
    if (codeActiveTab === 'file') return;
    if (!generatedDraftDirty || generatedDraftKey !== generatedDraftSourceKey) {
      setGeneratedDraft(currentCode);
      setGeneratedDraftKey(generatedDraftSourceKey);
      setGeneratedDraftDirty(false);
      setGeneratedApplyStatus('idle');
      setGeneratedApplyMessage('');
    }
  }, [codeActiveTab, currentCode, generatedDraftDirty, generatedDraftKey, generatedDraftSourceKey]);

  // Handle automatic synchronization to folder on workspace edits
  useEffect(() => {
    if (autoSaveEnabled && modWorkspacePath) {
      saveToDirectory(false);
    }
    // reason: saveToDirectory is a plain function recreated each render; adding it would run the effect every render. Effect should fire only when the serialized workspace or autosave flags change.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workspaceSerialized, autoSaveEnabled, modWorkspacePath]);

  // Synchronise base template references initially or on compile
  useEffect(() => {
    if (!initialMDCode && mdCode) {
      setInitialMDCode(mdCode);
    }
    if (!initialUICode && uiCode) {
      setInitialUICode(uiCode);
    }
    if (!originalMD && mdCode) {
      setOriginalMD(mdCode);
    }
    if (!originalUI && uiCode) {
      setOriginalUI(uiCode);
    }
    // reason: one-shot baseline capture; re-running on the initial*/original* deps would clobber the captured baselines.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mdCode, uiCode]);

  // Synchronise files selected in the project sidebar
  useEffect(() => {
    if (activeEditorFile) {
      // Ensure tab exists
      setOpenTabs(prev => {
        if (prev.some(t => t.id === activeEditorFile.path)) {
          return prev;
        }
        return [...prev, { id: activeEditorFile.path, name: activeEditorFile.name, path: activeEditorFile.path, type: 'file' as const }];
      });
      // Ensure file exists in cache
      setOpenFilesMap(prev => {
        if (prev[activeEditorFile.path]) {
          return prev;
        }
        return {
          ...prev,
          [activeEditorFile.path]: {
            name: activeEditorFile.name,
            path: activeEditorFile.path,
            content: activeEditorFile.content,
            originalContent: activeEditorFile.content
          }
        };
      });
      setCodeActiveTab('file');
      setEditorContent(activeEditorFile.content);
      setEditorSaveStatus('idle');
      setEditorError('');
    }
    // reason: intentionally keyed on the file path only — this effect should fire when the selected file changes, not on unrelated identity changes of the activeEditorFile object.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeEditorFile?.path]);

  const handleEditorContentChange = (val: string) => {
    setEditorContent(val);
    if (activeEditorFile) {
      setOpenFilesMap(prev => {
        if (!prev[activeEditorFile.path]) return prev;
        return {
          ...prev,
          [activeEditorFile.path]: {
            ...prev[activeEditorFile.path],
            content: val
          }
        };
      });
    }
  };

  const activeCodeText = codeActiveTab === 'file'
    ? editorContent
    : (generatedDraft || currentCode);

  const handleGeneratedDraftChange = (val: string) => {
    setGeneratedDraft(val);
    setGeneratedDraftDirty(val !== currentCode);
    setGeneratedApplyStatus('idle');
    setGeneratedApplyMessage('');
  };

  const applyGeneratedCodeEdit = () => {
    if (!setWorkspace) {
      setGeneratedApplyStatus('error');
      setGeneratedApplyMessage('Workspace editing is not available in this view.');
      return;
    }
    if (codeActiveTab !== 'md') {
      setGeneratedApplyStatus('error');
      setGeneratedApplyMessage('Only Mission Director XML has a safe parser-backed apply path right now.');
      return;
    }
    if (selectedNode || selectedCueIds.length > 0) {
      setGeneratedApplyStatus('error');
      setGeneratedApplyMessage('Partial hierarchy edits are editable/copyable, but apply is gated until partial-graph merge is lossless. Switch to full MD.xml to apply.');
      return;
    }

    setGeneratedApplyStatus('applying');
    try {
      const parsed = parseXMLToWorkspace(generatedDraft);
      if (!parsed) {
        throw new Error('Could not parse edited Mission Director XML.');
      }
      const nextWorkspace: ModWorkspace = {
        ...workspace,
        name: parsed.name || workspace.name,
        version: parsed.version || workspace.version,
        author: parsed.author || workspace.author,
        description: parsed.description || workspace.description,
        nodes: parsed.nodes,
        links: parsed.links
      };
      saveCheckpoint?.(workspace);
      setWorkspace(nextWorkspace);
      setGeneratedDraftDirty(false);
      setGeneratedApplyStatus('applied');
      setGeneratedApplyMessage(`Applied ${parsed.nodes.length} parsed MD nodes back into the workspace.`);
      setTimeout(() => setGeneratedApplyStatus('idle'), 2500);
    } catch (err) {
      setGeneratedApplyStatus('error');
      setGeneratedApplyMessage(messageFromUnknown(err, 'Could not apply edited XML.'));
    }
  };

  const handleSelectTab = (tab: Tab) => {
    if (tab.type === 'md') {
      setCodeActiveTab('md');
      setActiveEditorFile(null);
    } else if (tab.type === 'ui') {
      setCodeActiveTab('ui');
      setActiveEditorFile(null);
    } else if (tab.type === 'node') {
      setCodeActiveTab('node');
    } else if (tab.type === 'file' && tab.path) {
      const fileData = openFilesMap[tab.id];
      if (fileData) {
        setActiveEditorFile({
          name: fileData.name,
          path: fileData.path,
          content: fileData.content
        });
        setCodeActiveTab('file');
        setEditorContent(fileData.content);
      }
    }
  };

  const handleCloseTab = (tabId: string) => {
    setOpenTabs(prev => {
      const filtered = prev.filter(t => t.id !== tabId);
      // If closing the active tab, fallback to another active or default md
      const isClosingActiveFile = codeActiveTab === 'file' && activeEditorFile?.path === tabId;
      if (isClosingActiveFile) {
        const remainingFiles = filtered.filter(t => t.type === 'file');
        if (remainingFiles.length > 0) {
          const nextFile = remainingFiles[remainingFiles.length - 1];
          setTimeout(() => handleSelectTab(nextFile), 0);
        } else {
          setCodeActiveTab('md');
          setActiveEditorFile(null);
        }
      }
      return filtered;
    });

    setOpenFilesMap(prev => {
      const copy = { ...prev };
      delete copy[tabId];
      return copy;
    });
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(activeCodeText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([activeCodeText], { type: 'text/xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = codeActiveTab === 'md' 
      ? `${workspace.name || 'custom_md_script'}.xml` 
      : codeActiveTab === 'ui'
      ? `${workspace.name || 'custom_menu_layout'}_ui.xml`
      : activeEditorFile?.name || 'edited_file.xml';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Memory-leak-safe, super-fast line block aligner for side-by-side IDE visual comparisons
  const computeLineDiff = (oldLines: string[], newLines: string[]): { 
    originalLines: DiffLine[]; 
    modifiedLines: DiffLine[]; 
    unifiedLines: DiffLine[]; 
  } => {
    // If either is too large, use a fast simple line matching or simple slider to protect resources
    if (oldLines.length > 2500 || newLines.length > 2500) {
      const originalLines: DiffLine[] = oldLines.map((l, idx) => ({ type: 'removed', value: l, originalLineNumber: idx + 1 }));
      const modifiedLines: DiffLine[] = newLines.map((l, idx) => ({ type: 'added', value: l, modifiedLineNumber: idx + 1 }));
      const unifiedLines: DiffLine[] = [
        ...oldLines.map((l, idx) => ({ type: 'removed' as const, value: l, originalLineNumber: idx + 1 })),
        ...newLines.map((l, idx) => ({ type: 'added' as const, value: l, modifiedLineNumber: idx + 1 }))
      ];
      return { originalLines, modifiedLines, unifiedLines };
    }

    const m = oldLines.length;
    const n = newLines.length;
    const dp: number[][] = [];
    for (let i = 0; i <= m; i++) {
      dp[i] = new Array(n + 1).fill(0);
    }

    for (let i = 1; i <= m; i++) {
      for (let j = 1; j <= n; j++) {
        if (oldLines[i - 1] === newLines[j - 1]) {
          dp[i][j] = dp[i - 1][j - 1] + 1;
        } else {
          dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
        }
      }
    }

    let i = m;
    let j = n;
    
    const revOriginal: DiffLine[] = [];
    const revModified: DiffLine[] = [];
    const revUnified: DiffLine[] = [];

    while (i > 0 || j > 0) {
      if (i > 0 && j > 0 && oldLines[i - 1] === newLines[j - 1]) {
        const lineVal = oldLines[i - 1];
        revOriginal.push({ type: 'unchanged', value: lineVal, originalLineNumber: i, modifiedLineNumber: j });
        revModified.push({ type: 'unchanged', value: lineVal, originalLineNumber: i, modifiedLineNumber: j });
        revUnified.push({ type: 'unchanged', value: lineVal, originalLineNumber: i, modifiedLineNumber: j });
        i--;
        j--;
      } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
        revOriginal.push({ type: 'empty', value: '', modifiedLineNumber: j });
        revModified.push({ type: 'added', value: newLines[j - 1], modifiedLineNumber: j });
        revUnified.push({ type: 'added', value: newLines[j - 1], modifiedLineNumber: j });
        j--;
      } else {
        revOriginal.push({ type: 'removed', value: oldLines[i - 1], originalLineNumber: i });
        revModified.push({ type: 'empty', value: '', originalLineNumber: i });
        revUnified.push({ type: 'removed', value: oldLines[i - 1], originalLineNumber: i });
        i--;
      }
    }

    return {
      originalLines: revOriginal.reverse(),
      modifiedLines: revModified.reverse(),
      unifiedLines: revUnified.reverse()
    };
  };

  const getDiffTexts = (): { original: string, current: string } => {
    let original = '';
    let current = '';

    if (codeActiveTab === 'md') {
      if (snapshotDiffWorkspace) {
        const snapSelected = selectedNode
          ? snapshotDiffWorkspace.nodes?.find(n => n.id === selectedNode.id) || null
          : null;
        original = snapSelected
          ? generateSelectedNodeHierarchyXML(snapSelected, snapshotDiffWorkspace)
          : generateMDXML(snapshotDiffWorkspace, selectedCueIds);
      } else {
        const baseWorkspace = diffBaseType === 'compile' 
          ? (lastCompiledWorkspace || initialWorkspace || workspace)
          : (initialWorkspace || workspace);
        const baseSelected = selectedNode
          ? baseWorkspace.nodes?.find(n => n.id === selectedNode.id) || null
          : null;
        original = baseSelected
          ? generateSelectedNodeHierarchyXML(baseSelected, baseWorkspace)
          : generateMDXML(baseWorkspace, selectedCueIds);
      }
      current = activeCodeText;
    } else if (codeActiveTab === 'ui') {
      if (snapshotDiffWorkspace) {
        original = generateUIXML(snapshotDiffWorkspace);
      } else {
        original = diffBaseType === 'compile' ? (originalUI || uiCode) : (initialUICode || uiCode);
      }
      current = activeCodeText;
    } else if (codeActiveTab === 'node') {
      current = activeCodeText;
      if (snapshotDiffWorkspace && selectedNode) {
        const snapNode = snapshotDiffWorkspace.nodes?.find(n => n.id === selectedNode.id);
        original = snapNode ? generateSelectedNodeHierarchyXML(snapNode, snapshotDiffWorkspace) : '';
      } else {
        original = '';
      }
    } else if (codeActiveTab === 'file') {
      current = activeCodeText;
      if (activeEditorFile) {
        if (snapshotDiffWorkspace) {
          original = getSnapshotContentForPath(snapshotDiffWorkspace, activeEditorFile.path);
        } else {
          original = openFilesMap[activeEditorFile.path]?.originalContent || activeEditorFile.content;
        }
      }
    }

    return { original, current };
  };

  const saveToDirectory = async (showFeedback: boolean) => {
    if (!modWorkspacePath) return;
    if (showFeedback) {
      setSyncStatus('syncing');
    }
    try {
      // Audit R4: deploy-verify (full 9-stage preflight) replaces the deprecated /deploy.
      const deployRes = await fetch('/api/agent/deploy-verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ workspace })
      });
      const deployData = await deployRes.json();
      if (deployRes.ok && deployData.ok) {
        if (showFeedback) {
          setSyncStatus('success');
          setTimeout(() => setSyncStatus('idle'), 2000);
        }
      } else {
        const failed = (deployData.checklist || []).find((c: { status: string }) => c.status === 'fail');
        throw new Error(deployData.error || (failed ? `${failed.label}: ${failed.detail}` : "Failed to deploy on server."));
      }
    } catch (err) {
      console.error("Playtest Directory Sync Error:", err);
      if (showFeedback) {
        setSyncStatus('error');
        setSyncErrorMsg(messageFromUnknown(err, "Disk write access refused."));
        setTimeout(() => setSyncStatus('idle'), 5000);
      }
    }
  };

  // NOTE: All packaging/compiler helpers (mod id, content.xml, per-domain XML generators,
  // file writers, snapshots, and package validation) now live in src/lib/modCompiler.ts and
  // are shared by both the auto-sync and Compile paths via compileAndSaveAll(). The previous
  // in-component duplicates were removed during the compiler consolidation.

  const onCompileModProject = async () => {
    await handleCompileModProject();
    setToolActiveTab('playtest');
  };

  // Memo cache for whole-file highlighting: the regex passes are O(file size) and the
  // same strings are re-highlighted on every render (drag, scroll, state changes).
  // Keyed by the input string itself — V8 caches string hashes, and the generated
  // text keeps the same instance between renders, so hits are cheap. Small cap keeps
  // memory bounded when many distinct files are viewed.
  const highlightCacheRef = React.useRef(new Map<string, string>());

  const highlightXML = (rawXML: string) => {
    const cache = highlightCacheRef.current;
    const cached = cache.get(rawXML);
    if (cached !== undefined) return cached;

    const escaped = rawXML
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
    // Large-file guard: the span-wrapping regex passes below are O(file size) and run on
    // every render. For very large generated files (e.g. deadair's 868KB MD) that freezes
    // the viewer, so above the threshold we skip coloring and return escaped text only —
    // still fully readable and editable, just monochrome (standard large-file IDE behavior).
    const out = escaped.length > 100000 ? escaped : escaped
      // Color attributes FIRST (on the escaped text) so the tag/comment passes below
      // don't re-match the class="..." attributes of the <span>s we inject here.
      .replace(/([a-zA-Z0-9_:-]+)=(&quot;|")([^"&]*)(&quot;|")/g, '<span class="text-purple-400">$1</span>=<span class="text-emerald-300">$2$3$4</span>')
      .replace(/(&lt;\/?[a-zA-Z0-9_:-]+)(\s|&gt;)/g, '<span class="text-cyan-400 font-semibold">$1</span>$2')
      .replace(/(&lt;!--[\s\S]*?--&gt;)/g, '<span class="text-slate-500 font-mono italic">$1</span>');

    if (cache.size > 12) cache.clear();
    cache.set(rawXML, out);
    return out;
  };

  // Pick a searchable token for a diagnostic so we can locate its line in the generated code.
  const getDiagToken = (d: PackageDiagnostic): string | null => {
    if (d.sourceRef?.label) return d.sourceRef.label;
    if (d.sourceRef?.id && !/^(cue|node|event|action|condition)_/.test(d.sourceRef.id)) return d.sourceRef.id;
    const m = (d.message || '').match(/"([^"]+)"/);
    return m ? m[1] : null;
  };

  // Map each diagnostic to a 0-based line index in the given code (by explicit line, or token match).
  const computeLineDiagMap = (code: string, diags: PackageDiagnostic[]) => {
    const map = new Map<number, { severity: string; messages: string[] }>();
    const lines = code.split('\n');
    diags.forEach(d => {
      let idx = -1;
      if (typeof d.line === 'number' && d.line >= 1 && d.line <= lines.length) {
        idx = d.line - 1;
      } else {
        const token = getDiagToken(d);
        if (token) idx = lines.findIndex(l => l.includes(token));
      }
      if (idx >= 0) {
        const ex = map.get(idx);
        const severity = (ex?.severity === 'error' || d.severity === 'error') ? 'error' : (ex?.severity || d.severity || 'warning');
        map.set(idx, { severity, messages: [...(ex?.messages || []), d.message] });
      }
    });
    return map;
  };


  const highlightCodeCacheRef = React.useRef(new Map<string, { ext: string | undefined; out: string }>());

  const highlightCode = (rawText: string) => {
    const ext = activeEditorFile?.name.split('.').pop()?.toLowerCase();
    const cache = highlightCodeCacheRef.current;
    const cached = cache.get(rawText);
    if (cached !== undefined && cached.ext === ext) return cached.out;

    let out: string;
    // Large-file guard (see highlightXML): skip coloring for big files to keep the editor responsive.
    if (rawText.length > 100000) {
      out = rawText.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    } else if (ext === 'json') {
      out = rawText
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/("(?:\\.|[^"\\])*")(\s*:)/g, '<span class="text-purple-400">$1</span>$2')
        .replace(/:\s*("(?:\\.|[^"\\])*")/g, ': <span class="text-emerald-300">$1</span>')
        .replace(/\b(true|false|null)\b/g, '<span class="text-amber-400">$1</span>');
    } else {
      out = highlightXML(rawText);
    }

    if (cache.size > 12) cache.clear();
    cache.set(rawText, { ext, out });
    return out;
  };

  const renderMinimap = (lines: { type?: string; value: string }[]) => {
    return (
      <div className="w-10 shrink-0 border-l border-white/5 bg-[#08090d] select-none overflow-hidden flex flex-col justify-start relative pointer-events-none pr-0.5">
        <div className="absolute inset-0 flex flex-col py-2 pointer-events-none overflow-hidden scale-y-95 opacity-80 select-none">
          {lines.slice(0, 160).map((line, idx) => {
            const isAdded = line.type === 'added';
            const isRemoved = line.type === 'removed';
            
            let trackColor = 'bg-slate-700/25';
            if (isAdded) {
              trackColor = 'bg-[#10b981]/45';
            } else if (isRemoved) {
              trackColor = 'bg-[#ef4444]/45';
            } else {
              const val = line.value.trim();
              if (val.startsWith('<cue') || val.startsWith('</cue')) {
                trackColor = 'bg-amber-400/45';
              } else if (val.startsWith('<event') || val.startsWith('<action')) {
                trackColor = 'bg-cyan-400/40';
              } else if (val.startsWith('<')) {
                trackColor = 'bg-purple-400/30';
              } else if (val.length > 0) {
                trackColor = 'bg-slate-650/15';
              }
            }

            const spaceCount = line.value.length - line.value.trimStart().length;
            const indent = Math.min(spaceCount * 0.8, 12);

            return (
              <div key={idx} className="flex h-[2px] items-center my-[0.8px]" style={{ paddingLeft: `${indent}px` }}>
                <div className={`h-[1px] rounded ${trackColor}`} style={{ width: `${Math.max(4, Math.min(22, line.value.trim().length / 2))}px` }} />
              </div>
            );
          })}
        </div>
      </div>
    );
  };

  const renderHighlightedTextarea = (
    value: string,
    onChange: (value: string) => void,
    ariaLabel: string,
    paddingClass: string,
    scroll: { top: number; left: number },
    setScroll: React.Dispatch<React.SetStateAction<{ top: number; left: number }>>,
    toneClass = 'text-slate-300'
  ) => (
    <>
      <pre
        aria-hidden="true"
        className={`absolute inset-0 ${paddingClass} font-mono text-xs leading-relaxed whitespace-pre pointer-events-none select-none overflow-hidden ${toneClass}`}
        style={{ transform: `translate(${-scroll.left}px, ${-scroll.top}px)` }}
        dangerouslySetInnerHTML={{ __html: `${highlightXML(value)}\n` }}
      />
      <textarea
        value={value}
        onChange={e => onChange(e.target.value)}
        onScroll={e => {
          const target = e.currentTarget;
          setScroll({ top: target.scrollTop, left: target.scrollLeft });
        }}
        spellCheck={false}
        className={`absolute inset-0 w-full h-full resize-none ${paddingClass} bg-transparent text-transparent caret-cyan-300 selection:bg-cyan-500/25 outline-none font-mono text-xs leading-relaxed whitespace-pre overflow-auto scrollbar-thin`}
        aria-label={ariaLabel}
      />
    </>
  );

  const isFileEditorActive = codeActiveTab === 'file' && !!activeEditorFile;
  // Memoized: splitting + token-searching a large generated file on every render is
  // O(file size × diagnostics) — only recompute when the text or diagnostics change.
  const codeLines = React.useMemo(() => activeCodeText.split('\n'), [activeCodeText]);
  const lineDiagMap = React.useMemo(
    () => computeLineDiagMap(activeCodeText, diagnostics),
    // reason: computeLineDiagMap is a plain function recreated each render; the real inputs are activeCodeText and diagnostics, so memoizing on those is correct.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [activeCodeText, diagnostics]
  );
  const renderTopBar = (content: React.ReactNode) => (
    topBarTarget ? createPortal(content, topBarTarget) : content
  );

  return (
    <div ref={setEditorRoot} id="antigravity_ide_container" className="flex flex-col flex-1 w-full min-w-0 h-full min-h-0 bg-[#0b0d12] text-slate-100 rounded-lg overflow-hidden border border-white/5 shadow-2xl relative">
      {/* Tab strip + compact actions — PORTALED into the persistent top bar (App) so the
          editor body is a code-only entity. Inline fallback when no portal target. */}
      {renderTopBar((
        <div className="bg-[#0b0d12] border-b border-white/5 select-none flex items-center justify-between w-full pl-1">
        <div className="flex items-center divide-x divide-white/5 overflow-x-auto scrollbar-none flex-1">
          {openTabs.map(tab => {
            const isActive = 
              (tab.id === 'md' && codeActiveTab === 'md') ||
              (tab.id === 'ui' && codeActiveTab === 'ui') ||
              (tab.id === 'node' && codeActiveTab === 'node') ||
              (tab.type === 'file' && codeActiveTab === 'file' && activeEditorFile?.path === tab.id);

            const isUnsaved = tab.type === 'file' && openFilesMap[tab.id] 
              ? openFilesMap[tab.id].content !== openFilesMap[tab.id].originalContent 
              : false;

            return (
              <div
                key={tab.id}
                className={`flex items-center h-9 px-3.5 border-r border-[#151722] font-mono cursor-pointer transition-all shrink-0 select-none relative group ${
                  isActive 
                    ? 'bg-[#181d2a] text-[#5fc3e4] border-t-2 border-cyan-400 font-bold'
                    : 'bg-[#0a0c10]/50 text-slate-500 hover:bg-[#131720]/80 hover:text-slate-300'
                }`}
                onClick={() => handleSelectTab(tab)}
              >
                <span className="mr-2 select-none">
                  {tab.type === 'md' && <FileCode className="w-3.5 h-3.5 text-cyan-400" />}
                  {tab.type === 'ui' && <FileJson className="w-3.5 h-[#fc5dbb]" />}
                  {tab.type === 'node' && <Terminal className="w-3.5 h-3.5 text-amber-400" />}
                  {tab.type === 'file' && (
                    tab.name.endsWith('.json') ? <FileJson className="w-3.5 h-3.5 text-emerald-400" /> :
                    tab.name.endsWith('.tsx') || tab.name.endsWith('.ts') ? <span className="text-[#3178c6] text-[10px] font-black shrink-0 select-none">TS</span> :
                    <FileCode className="w-3.5 h-3.5 text-blue-400" />
                  )}
                </span>

                <span className="text-[10px] tracking-tight">{tab.name}</span>

                {tab.type === 'file' && (
                  <button
                    type="button"
                    className="ml-2 p-0.5 rounded hover:bg-white/10 text-slate-500 hover:text-white transition-all cursor-pointer"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleCloseTab(tab.id);
                    }}
                  >
                    {isUnsaved ? (
                      <span className="block w-1.5 h-1.5 rounded-full bg-amber-400 group-hover:hidden" />
                    ) : null}
                    <X className={`w-3 h-3 ${isUnsaved ? 'hidden group-hover:block animate-pulse' : 'opacity-40 group-hover:opacity-100'}`} />
                  </button>
                )}
              </div>
            );
          })}
        </div>

        {/* COMPACT ICON-ONLY ACTIONS — the editor's single control strip (right of the tabs). */}
        <div className="flex items-center gap-0.5 px-1.5 shrink-0 select-none border-l border-white/5">
          <button
            onClick={() => setDiffEnabled(!diffEnabled)}
            title={`Diff viewer: ${effectiveDiffEnabled ? 'on' : 'off'}`}
            className={`p-1 rounded transition-all cursor-pointer ${effectiveDiffEnabled ? 'bg-amber-500/15 text-amber-400' : 'text-slate-500 hover:text-slate-300 hover:bg-white/5'}`}
          >
            <Sparkles className="w-3.5 h-3.5" />
          </button>
          {effectiveDiffEnabled && (
            <button
              onClick={() => setDiffMode(diffMode === 'split' ? 'unified' : 'split')}
              title={`Diff mode: ${diffMode}`}
              className="p-1 rounded text-slate-400 hover:text-cyan-400 hover:bg-white/5 transition-all cursor-pointer"
            >
              <Split className="w-3.5 h-3.5" />
            </button>
          )}
          {codeActiveTab === 'md' && (() => {
            const cues = (workspace.nodes || []).filter(n => n.type === 'cue');
            const stems = Array.from(new Set(cues.map(c => (c.properties as any)?.mdFileStem).filter((s: any): s is string => typeof s === 'string')));
            if (stems.length <= 1) return null;
            return (
              <>
                <span className="w-px h-4 bg-white/10 mx-0.5" />
                <select
                  value={activeMdScript ?? '__all__'}
                  onChange={e => setActiveMdScript?.(e.target.value === '__all__' ? null : e.target.value)}
                  title="View all scripts together, or one at a time"
                  className="bg-slate-800 text-slate-200 text-xs rounded px-1 py-0.5 border border-white/10 cursor-pointer max-w-[160px]"
                >
                  <option value="__all__">All scripts ({stems.length})</option>
                  {stems.map(s => <option key={s} value={s}>{s}.xml</option>)}
                </select>
              </>
            );
          })()}
          <span className="w-px h-4 bg-white/10 mx-0.5" />
          <button
            onClick={onCompileModProject}
            disabled={compileStatus === 'compiling'}
            title="Compile whole workspace"
            className="p-1 rounded text-emerald-400 hover:text-white hover:bg-emerald-500/20 transition-all cursor-pointer disabled:opacity-40"
          >
            <PackageCheck className="w-3.5 h-3.5" />
          </button>
          {codeActiveTab !== 'file' && (
            <button
              onClick={applyGeneratedCodeEdit}
              disabled={!generatedDraftDirty || generatedApplyStatus === 'applying'}
              title="Apply edited XML back into the workspace"
              className="p-1 rounded text-cyan-300 hover:text-white hover:bg-cyan-500/20 transition-all cursor-pointer disabled:opacity-30 disabled:cursor-not-allowed"
            >
              <Save className="w-3.5 h-3.5" />
            </button>
          )}
          <button onClick={copyToClipboard} title="Copy active code" className="p-1 rounded text-slate-400 hover:text-cyan-400 hover:bg-white/5 transition-all cursor-pointer">
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Clipboard className="w-3.5 h-3.5" />}
          </button>
          <button onClick={downloadFile} title="Download active file" className="p-1 rounded text-slate-400 hover:text-cyan-400 hover:bg-white/5 transition-all cursor-pointer">
            <Download className="w-3.5 h-3.5" />
          </button>
        </div>
        </div>
      ))}

      {/* Breadcrumb removed — the active tab already names the file; keeps the editor window clean.
          Kept only for directory-file editing, where the full path matters. */}
      {codeActiveTab === 'file' && activeEditorFile && (
        <div className="bg-[#0b0d12] py-1 px-4 text-[9px] text-slate-500 font-mono border-b border-white/5 flex items-center select-none shrink-0">
          <Folder className="w-3.5 h-3.5 text-cyan-500/80 shrink-0 mr-1.5" />
          <span className="truncate flex items-center gap-1">
            {activeEditorFile.path.split('/').map((seg, idx, arr) => (
              <React.Fragment key={seg}>
                <span className={idx === arr.length - 1 ? 'text-slate-300 font-medium' : 'text-slate-600'}>{seg}</span>
                {idx < arr.length - 1 && <span className="text-slate-700 inline">&gt;</span>}
              </React.Fragment>
            ))}
          </span>
        </div>
      )}

      {/* ================================================================ */}
      {/* SNAPSHOT DIFF MODE BANNER                                        */}
      {/* ================================================================ */}
      {snapshotDiffWorkspace && (
        <div className="bg-gradient-to-r from-cyan-950/80 via-slate-900 to-[#0c0e14] border-b border-cyan-500/30 px-4 py-2 flex items-center justify-between font-mono text-xs select-none">
          <div className="flex items-center gap-2.5">
            <div className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse shrink-0" />
            <span className="text-cyan-400 font-bold uppercase tracking-wider text-[10px] shrink-0">Snapshot Diff Active</span>
            <span className="text-slate-650 select-none">|</span>
            <span className="text-slate-400 text-[10px] truncate">
              Comparing current workspace against snapshot: <span className="text-cyan-300 font-bold">{snapshotDiffWorkspace.name}</span>
            </span>
          </div>
          <button
            onClick={onClearSnapshotDiff}
            className="px-2.5 py-1 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 hover:text-white border border-cyan-500/30 rounded text-[9px] font-bold tracking-wider uppercase transition-all flex items-center gap-1 cursor-pointer shrink-0"
          >
            <X className="w-3 h-3" />
            Close Diff
          </button>
        </div>
      )}

      {/* ================================================================ */}
      {/* VIEWPANE STAGE (DIFF MODE OR NORMAL CODE EDITOR)                  */}
      {/* ================================================================ */}
      <div id="xml_code_viewport" className="flex-1 flex min-h-0 relative select-text overflow-hidden m-2 rounded-lg border border-white/10 bg-[#050608] shadow-[0_3px_14px_rgba(0,0,0,0.45)]">
        {CODEMIRROR_EDITOR ? (
          effectiveDiffEnabled ? (
            // ============= CODEMIRROR DIFF (read-only, split/unified) =============
            <div className="flex-1 flex overflow-hidden min-h-0 bg-[#050608]">
              <div className="flex-1 min-w-0 overflow-hidden">
                <CodeMirrorField
                  value={getDiffTexts().current}
                  diffOriginal={getDiffTexts().original}
                  diffMode={diffMode}
                  className="h-full"
                />
              </div>
              {showMinimap && renderMinimap(computeLineDiff(getDiffTexts().original.split('\n'), getDiffTexts().current.split('\n')).modifiedLines)}
            </div>
          ) : (
            // ============= CODEMIRROR NORMAL (editable) =============
            <div className="flex-1 flex overflow-hidden min-h-0">
              <div className="relative h-full w-full overflow-hidden flex flex-1 bg-[#050608]">
                <div className="flex-1 min-w-0 overflow-hidden">
                  <CodeMirrorField
                    value={isFileEditorActive ? editorContent : activeCodeText}
                    onChange={isFileEditorActive ? handleEditorContentChange : handleGeneratedDraftChange}
                    className="h-full"
                  />
                </div>
                {/* Status pill — file save vs generated apply (preserved from the old editor) */}
                <div className="absolute bottom-3 right-4 px-2 py-1 rounded bg-[#0b0c13]/90 border border-white/5 text-[9px] pointer-events-none select-none z-10 font-mono">
                  {isFileEditorActive ? (
                    editorSaveStatus === 'error' ? <span className="text-red-400 font-bold uppercase">{editorError}</span>
                    : editorSaveStatus === 'saving' ? <span className="text-cyan-400 animate-pulse">SAVING ON-DISK...</span>
                    : editorSaveStatus === 'saved' ? <span className="text-[#36e07a] font-bold">✔ DRAFT DEPLOYED TO BLUEPRINT</span>
                    : <span className="text-slate-500 lowercase">{activeEditorFile?.path}</span>
                  ) : (
                    generatedApplyStatus === 'error' ? <span className="text-red-400 font-bold uppercase">{generatedApplyMessage}</span>
                    : generatedApplyStatus === 'applying' ? <span className="text-cyan-400 animate-pulse">APPLYING XML...</span>
                    : generatedApplyStatus === 'applied' ? <span className="text-[#36e07a] font-bold">{generatedApplyMessage}</span>
                    : generatedDraftDirty ? <span className="text-amber-300 font-bold">DRAFT MODIFIED - APPLY TO WORKSPACE WHEN READY</span>
                    : <span className="text-slate-500 lowercase">generated XML is editable</span>
                  )}
                </div>
              </div>
              {/* Error scroll indicators (approximate) — preserved */}
              {lineDiagMap.size > 0 && (
                <div className="absolute top-0 right-1 w-2.5 h-full pointer-events-none z-10">
                  {Array.from(lineDiagMap.entries()).map(([idx, info]) => (
                    <div
                      key={idx}
                      className={`absolute right-0 w-2 h-[3.5px] rounded-sm ${info.severity === 'error' ? 'bg-red-500' : 'bg-amber-400'}`}
                      style={{ top: `${(idx / Math.max(codeLines.length, 1)) * 100}%` }}
                    />
                  ))}
                </div>
              )}
              {showMinimap && renderMinimap(codeLines.map(l => ({ value: l })))}
            </div>
          )
        ) : effectiveDiffEnabled ? (
          diffMode === 'split' ? (
            // ==================== SIDE-BY-SIDE DIFF MODE ====================
            <div className="flex-1 flex overflow-hidden min-h-0 bg-[#050608]">
              {/* Sync viewport inside a single vertical scrollbar space */}
              <div className="flex-1 overflow-auto scrollbar-thin flex min-h-0 select-text">
                <div className="flex flex-grow min-w-[750px] divide-x divide-white/5">
                  
                  {/* Left Lane: Reference Source */}
                  <div className="flex-1 bg-[#050608]/98 select-text">
                    <div className="sticky top-0 z-10 bg-[#11131a] border-b border-white/5 py-1.5 px-3.5 font-mono text-[9px] text-[#ef4444] font-bold flex items-center justify-between select-none">
                      <span>ORIGINAL REFERENCE</span>
                      <span className="text-[7.5px] bg-red-950/40 px-1.5 py-0.5 rounded border border-red-500/20 uppercase tracking-widest">BASELINE</span>
                    </div>
                    <div className="py-2.5 text-xs font-mono leading-relaxed">
                      {computeLineDiff(getDiffTexts().original.split('\n'), getDiffTexts().current.split('\n')).originalLines.map((line, i) => {
                        const isRemoved = line.type === 'removed';
                        const isEmpty = line.type === 'empty';
                        
                        let lineBg = 'hover:bg-white/[0.01]';
                        let textColor = 'text-slate-500';
                        if (isRemoved) {
                          lineBg = 'bg-[#ef4444]/10 border-l-2 border-[#ef4444]';
                          textColor = 'text-red-300';
                        } else if (isEmpty) {
                          lineBg = 'bg-[#151720]/15 text-transparent opacity-5 select-none pointer-events-none';
                        }

                        return (
                          <div key={i} className={`flex h-[18px] items-center ${lineBg}`}>
                            <span className="select-none text-right pr-2.5 pl-2 w-10 shrink-0 text-slate-650 text-[9.5px]">
                              {line.originalLineNumber || ''}
                            </span>
                            <span className="select-none w-4 text-center shrink-0 pr-1 text-[#ef4444] text-[9.5px] font-black">
                              {isRemoved ? '-' : ''}
                            </span>
                            <span
                              className={`flex-1 whitespace-pre pr-4 truncate ${textColor}`}
                              dangerouslySetInnerHTML={!isEmpty ? { __html: highlightXML(line.value) || '&nbsp;' } : undefined}
                            />
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  {/* Right Lane: Edited Working Document */}
                  <div className="flex-1 bg-[#050608]/98 select-text">
                    <div className="sticky top-0 z-10 bg-[#11131a] border-b border-white/5 py-1.5 px-3.5 font-mono text-[9px] text-[#22c55e] font-bold flex items-center justify-between select-none">
                      <span>EDITABLE WORKING STATE</span>
                      <span className="text-[7.5px] bg-emerald-950/40 px-1.5 py-0.5 rounded border border-emerald-500/20 uppercase tracking-widest">LIVE EDITOR</span>
                    </div>
                    <div className="relative h-[calc(100%-28px)] min-h-[420px]">
                      {renderHighlightedTextarea(
                        activeCodeText,
                        value => codeActiveTab === 'file' ? handleEditorContentChange(value) : handleGeneratedDraftChange(value),
                        'Editing latest code beside snapshot',
                        'py-2.5 pl-11 pr-4',
                        splitEditorScroll,
                        setSplitEditorScroll,
                        'text-emerald-200/90'
                      )}
                      <div className="absolute left-0 top-0 bottom-0 w-10 py-2.5 bg-[#050608] border-r border-white/5 text-right pr-2 select-none pointer-events-none font-mono text-[9.5px] leading-[19.5px] text-slate-650 overflow-hidden">
                        {activeCodeText.split('\n').slice(0, 4000).map((_, i) => (
                          <div key={i}>{i + 1}</div>
                        ))}
                      </div>
                    </div>
                  </div>

                </div>
              </div>

              {/* Synchronous Minimap */}
              {showMinimap && renderMinimap(computeLineDiff(getDiffTexts().original.split('\n'), getDiffTexts().current.split('\n')).modifiedLines)}
            </div>
          ) : (
            // ==================== UNIFIED STACKED DIFF MODE ====================
            <div className="flex-1 flex overflow-hidden min-h-0 bg-[#050608]">
              <div className="flex-1 overflow-auto scrollbar-thin py-2 select-text">
                {computeLineDiff(getDiffTexts().original.split('\n'), getDiffTexts().current.split('\n')).unifiedLines.map((line, i) => {
                  const isAdded = line.type === 'added';
                  const isRemoved = line.type === 'removed';
                  
                  let lineBg = 'hover:bg-white/[0.01] border-l-2 border-transparent';
                  let textColor = 'text-slate-400';
                  let symbol = ' ';
                  let numText = '';

                  if (isAdded) {
                    lineBg = 'bg-[#22c55e]/10 border-l-2 border-[#22c55e]';
                    textColor = 'text-emerald-300';
                    symbol = '+';
                    numText = line.modifiedLineNumber ? `${line.modifiedLineNumber}` : '';
                  } else if (isRemoved) {
                    lineBg = 'bg-[#ef4444]/15 border-l-2 border-[#ef4444]';
                    textColor = 'text-red-300';
                    symbol = '-';
                    numText = line.originalLineNumber ? `${line.originalLineNumber}` : '';
                  } else {
                    numText = line.modifiedLineNumber ? `${line.modifiedLineNumber}` : `${line.originalLineNumber || ''}`;
                  }

                  return (
                    <div key={i} className={`flex h-[18px] items-center ${lineBg}`}>
                      <span className="select-none text-right pr-2.5 pl-2 w-10 shrink-0 text-slate-650 text-[9.5px]">
                        {numText}
                      </span>
                      <span className={`select-none w-4 text-center shrink-0 pr-1 text-[10px] font-black ${isAdded ? 'text-emerald-500' : isRemoved ? 'text-red-500' : 'text-slate-655'}`}>
                        {symbol}
                      </span>
                      <span
                        className={`flex-1 whitespace-pre pr-4 truncate ${textColor}`}
                        dangerouslySetInnerHTML={{ __html: highlightCode(line.value) || '&nbsp;' }}
                      />
                    </div>
                  );
                })}
              </div>

              {/* Unified Minimap */}
              {showMinimap && renderMinimap(computeLineDiff(getDiffTexts().original.split('\n'), getDiffTexts().current.split('\n')).unifiedLines)}
            </div>
          )
        ) : (
          // ==================== NORMAL WORKSPACE EDIT & DISPLAY ====================
          <div className="flex-1 flex overflow-hidden min-h-0">
            {isFileEditorActive ? (
              // EDITABLE INPUT FOR DIRECTORY FILES
              <div className="relative h-full w-full overflow-hidden flex flex-1 bg-[#050608]">
                <div className="flex-1 h-full relative overflow-auto scrollbar-thin">
                  <pre
                    aria-hidden="true"
                    className="absolute inset-0 p-4 whitespace-pre pt-3 pr-4 leading-relaxed font-mono text-xs select-none pointer-events-none text-transparent"
                    dangerouslySetInnerHTML={{ __html: highlightCode(editorContent) + '\n' }}
                  />
                  <textarea
                    value={editorContent}
                    onChange={e => handleEditorContentChange(e.target.value)}
                    spellCheck={false}
                    className="absolute inset-0 w-full h-full resize-none p-4 pt-3 pr-4 bg-transparent text-slate-300 caret-cyan-300 selection:bg-cyan-500/25 outline-none font-mono text-xs leading-relaxed whitespace-pre"
                    aria-label={`Editing ${activeEditorFile.name}`}
                  />
                </div>
                {/* Save status pill */}
                <div className="absolute bottom-3 right-4 px-2 py-1 rounded bg-[#0b0c13]/90 border border-white/5 text-[9px] text-slate-500 pointer-events-none select-none z-10 font-mono">
                  {editorSaveStatus === 'error' ? (
                    <span className="text-red-400 font-bold uppercase">{editorError}</span>
                  ) : editorSaveStatus === 'saving' ? (
                    <span className="text-cyan-400 animate-pulse">SAVING ON-DISK...</span>
                  ) : editorSaveStatus === 'saved' ? (
                    <span className="text-[#36e07a] font-bold">✔ DRAFT DEPLOYED TO BLUEPRINT</span>
                  ) : (
                    <span className="text-slate-500 lowercase">{activeEditorFile.path}</span>
                  )}
                </div>
              </div>
            ) : (
              // EDITABLE VIEWER FOR GENERATED XML TEMPLATES (MD, UI, NODE)
              <div className="relative h-full w-full overflow-hidden flex flex-1 bg-[#050608]">
                <div className="absolute left-0 top-0 bottom-0 w-11 py-3 bg-[#050608] border-r border-white/5 text-right pr-2 select-none pointer-events-none font-mono text-[9.5px] leading-[19.5px] text-slate-650 overflow-hidden">
                  {codeLines.slice(0, 4000).map((_, i) => (
                    <div key={i} className={lineDiagMap.has(i) ? (lineDiagMap.get(i)?.severity === 'error' ? 'text-red-400' : 'text-amber-300') : ''}>
                      {i + 1}
                    </div>
                  ))}
                </div>
                {renderHighlightedTextarea(
                  activeCodeText,
                  handleGeneratedDraftChange,
                  'Editing generated XML',
                  'py-3 pl-14 pr-12',
                  generatedEditorScroll,
                  setGeneratedEditorScroll
                )}
                <div className="absolute bottom-3 right-14 px-2 py-1 rounded bg-[#0b0c13]/90 border border-white/5 text-[9px] pointer-events-none select-none z-10 font-mono">
                  {generatedApplyStatus === 'error' ? (
                    <span className="text-red-400 font-bold uppercase">{generatedApplyMessage}</span>
                  ) : generatedApplyStatus === 'applying' ? (
                    <span className="text-cyan-400 animate-pulse">APPLYING XML...</span>
                  ) : generatedApplyStatus === 'applied' ? (
                    <span className="text-[#36e07a] font-bold">{generatedApplyMessage}</span>
                  ) : generatedDraftDirty ? (
                    <span className="text-amber-300 font-bold">DRAFT MODIFIED - APPLY TO WORKSPACE WHEN READY</span>
                  ) : (
                    <span className="text-slate-500 lowercase">generated XML is editable</span>
                  )}
                </div>
              </div>
            )}

            {/* Error indicators scroll-gutter */}
            {lineDiagMap.size > 0 && !effectiveDiffEnabled && (
              <div className="absolute top-0 right-1 w-2.5 h-full pointer-events-none z-10 selection:bg-transparent">
                {Array.from(lineDiagMap.entries()).map(([idx, info]) => (
                  <div
                    key={idx}
                    className={`absolute right-0 w-2 h-[3.5px] rounded-sm ${info.severity === 'error' ? 'bg-red-500' : 'bg-amber-400'}`}
                    style={{ top: `${(idx / Math.max(codeLines.length, 1)) * 100}%` }}
                  />
                ))}
              </div>
            )}

            {/* Render CSS Visual Code-Strips Minimap (auto-hidden in a narrow panel — G8b) */}
            {showMinimap && renderMinimap(codeLines.map(l => ({ value: l })))}
          </div>
        )}
      </div>

      {/* BOTTOM STATUS BAR — VS Code-style; file meta lives here now, not on the editor. */}
      <div className="bg-[#0b0d12] border-t border-white/5 px-4 py-1 flex items-center justify-between font-mono text-[9px] text-slate-500 select-none shrink-0">
        <div className="flex items-center gap-3">
          {effectiveDiffEnabled && !snapshotDiffWorkspace && (
            <div className="flex items-center gap-1.5">
              <span className="text-slate-600 uppercase text-[8px] font-extrabold tracking-wider">diff ref:</span>
              <select
                value={diffBaseType}
                onChange={(e) => setDiffBaseType(e.target.value as 'compile' | 'original')}
                className="bg-[#0c0d12] border border-white/10 text-[9px] text-slate-300 rounded px-1.5 py-0.5 outline-none font-mono focus:border-cyan-500/50 cursor-pointer"
              >
                <option value="compile">Last Compiled Build</option>
                <option value="original">Initial Loaded Template</option>
              </select>
            </div>
          )}
        </div>
        <div className="flex items-center gap-3">
          <span>UTF-8</span>
          <span className="text-slate-700">•</span>
          <span>{codeActiveTab === 'file' && activeEditorFile?.name.endsWith('.json') ? 'JSON' : 'XML / STRUCT'}</span>
          <span className="text-slate-700">•</span>
          <span>{diffEnabled ? 'DIFF_ACTIVE' : `LINES: ${codeLines.length}`}</span>
        </div>
      </div>
    </div>
  );
}
